/** Shared by constrained decoding and host unit contracts. Product details come from project sources. */
export const LIFECYCLE_INSTRUCTIONS = `Every new case includes lifecycle version 2. Completeness is explicit obligations, never a fixed or average step count. Classify what the case changes; each kind has its own obligation:
1. UI-only state (switching a tab, opening a panel/dialog/dropdown, typing into a field that is not saved): no obligation. Every case starts on a freshly opened entry page, so do NOT write postSteps to undo it; a case that only does this is mode read-only.
2. Session state (connect/disconnect wallet, switch network, log out): set session:"changed" — the runner discards that browser after the case. Do NOT write a postStep to reconnect. It can still be mode read-only.
3. A persisted setting (a preference or configuration that is still there after reload, e.g. a mode, level or default value the product saves): mode controlled, add settings:[{id,sourceRef,name,original,changedAfterStep,observed}] where original is the value shown before the case, observed is a screen check whose oracle value contains original, and one cleanup {id,settingId,postStep,verified} whose postStep sets it back to exactly original and whose verified oracle contains original.
4. A business resource the case creates: mode controlled, add resources:[{id,sourceRef,identityKind,identity,establishAfterStep,established,ownership,vacant?}] and one cleanup {id,resourceId,postStep,verified} per resource. Pick identityKind:
   - generated: the product shows a name you type; identity contains the literal \${env.TP_LIFECYCLE_ID}.
   - attribute: the product shows no custom label, so the resource is recognised by a value this execution chooses (e.g. a distinctive amount or price); identity contains a \${env.NAME} variable the preparer binds to that visible value, and the steps type that same variable.
   - slot: at most one such resource exists per key (e.g. one per account and item); identity is the key as shown on screen; vacant is a screen check proving the slot is empty before the case (and it is checked again by cleanup).
   The step at establishAfterStep (1-based) and the cleanup postStep must contain identity exactly. For generated/attribute, the established, ownership and cleanup verified oracles must each contain identity. Ownership also names the project-provided account/context.
5. Irreversible effects that cannot be undone (fees, consumed quota): list them in sideEffects; never assert that they are restored.
Always: version 2; mode read-only|controlled; rationale; sourceRefs bound to the case sources; supports $expected or assertion ids; baseline has one entry per precondition with statement equal to that exact precondition string, each with deterministic same-screen checks. Every postStep is referenced by exactly one cleanup; a read-only case has postSteps [] and resources/settings/cleanup []. Checks are {statement,checks:[{kind:"screen",statement,oracle:{kind:"text"|"noText",value}}]}; never a model declaration of verified state. Cleanup runs as compensation on failure too. A state the case needs but does not create itself (e.g. an existing record before closing or editing it) is a precondition, not a resource: keep the case and mark readiness blocked with the missing prerequisite. Recipes remain none/ui-only. No SUT API calls. Preparers cannot weaken the reviewed contract or move its action bindings.`;
const strings={type:'array',items:{type:'string',minLength:1}} as const;
const check={type:'object',additionalProperties:false,properties:{statement:{type:'string'},checks:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['screen']},statement:{type:'string'},oracle:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['text','noText']},value:{type:'string'}},required:['kind','value']}},required:['kind','statement','oracle']}}},required:['statement','checks']} as const;
const resource={type:'object',additionalProperties:false,properties:{id:{type:'string'},sourceRef:{type:'string'},identityKind:{type:'string',enum:['generated','attribute','slot']},identity:{type:'string'},establishAfterStep:{type:'integer',minimum:1},established:check,ownership:check,vacant:check},required:['id','sourceRef','identityKind','identity','establishAfterStep','established','ownership']} as const;
const setting={type:'object',additionalProperties:false,properties:{id:{type:'string'},sourceRef:{type:'string'},name:{type:'string'},original:{type:'string'},changedAfterStep:{type:'integer',minimum:1},observed:check},required:['id','sourceRef','name','original','changedAfterStep','observed']} as const;
const cleanup={type:'object',additionalProperties:false,properties:{id:{type:'string'},resourceId:{type:'string'},settingId:{type:'string'},postStep:{type:'integer',minimum:1},verified:check},required:['id','postStep','verified']} as const;
export const LIFECYCLE_JSON_SCHEMA={type:'object',additionalProperties:false,properties:{version:{type:'integer',enum:[2]},mode:{type:'string',enum:['read-only','controlled']},rationale:{type:'string'},sourceRefs:{...strings,minItems:1},supports:{...strings,minItems:1},baseline:{type:'array',minItems:1,items:check},session:{type:'string',enum:['unchanged','changed']},resources:{type:'array',items:resource},settings:{type:'array',items:setting},cleanup:{type:'array',items:cleanup},sideEffects:strings},required:['version','mode','rationale','sourceRefs','supports','baseline','session','resources','settings','cleanup','sideEffects']} as const;
