import {runOrigin} from '@/lib/workflowRuns';
import {useEffect,useState} from 'react';
import {useStore} from '@/lib/store';
import {useT} from '@/lib/prefs';
import {useProjectRuns} from '@/lib/useProjectRuns';
import {NeedProject} from '@/components/NeedProject';
import {TopBar} from '@/components/TopBar';
import {RevisionViewer} from '@/components/workbench/RevisionViewer';
import {readProjectContext,navigateProject} from '@/lib/projectContext';
export function WorkflowReports(){const projectId=useStore(s=>s.activeProjectId);return projectId?<Reports key={projectId} projectId={projectId}/>:<NeedProject/>;}
function Reports({projectId}:{projectId:string}){const t=useT(),{runs,loaded,error}=useProjectRuns(projectId),[ctx,setCtx]=useState(readProjectContext);useEffect(()=>{const h=()=>setCtx(readProjectContext());window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);const all=runs.flatMap(r=>r.revisions),reports=runs.filter(r=>!ctx.runId||r.id===ctx.runId).flatMap(r=>r.revisions.filter(a=>a.kind==='execution')).reverse(),selected=reports.find(r=>r.id===ctx.revisionId);return <main className="flex min-h-0 flex-1 flex-col"><TopBar title={t('surface.runs')}/><div className="border-b border-border p-4"><select aria-label={t('workflow.runList')} className="min-h-10 max-w-full rounded border border-border bg-background px-3 text-sm" value={ctx.runId} onChange={e=>navigateProject('runs',{projectId,runId:e.target.value,revisionId:''})}><option value="">{t('bench.allRuns')}</option>{runs.map(r=><option key={r.id} value={r.id}>{r.id.slice(-12)} · {t(`workflow.status.${r.status}`)} · {runOrigin(r)}</option>)}</select></div>{error&&<p role="alert" className="p-4 text-bad">{error}</p>}<div className="grid min-h-0 flex-1 grid-cols-[280px_1fr]"><aside className="overflow-auto border-r border-border">{reports.map(r=><button key={r.id} className={`block w-full border-b border-border p-4 text-left text-sm ${selected?.id===r.id?'bg-primary/10':''}`} onClick={()=>navigateProject('runs',{runId:r.runId,revisionId:r.id})}>{new Date(r.createdAt).toLocaleString()}<small className="mt-2 block font-mono text-muted-foreground">{r.runId.slice(-12)} · v{r.revision}</small></button>)}{loaded&&!reports.length&&<p className="p-5 text-sm text-muted-foreground">{t('bench.noReports')}</p>}</aside><section className="min-w-0 overflow-auto p-5">{selected?<RevisionViewer projectId={projectId} revision={selected} all={all} onSelect={r=>navigateProject('artifacts',{runId:r.runId,revisionId:r.id})}/>:<p className="text-sm text-muted-foreground">{t('bench.pickReport')}</p>}</section></div></main>;}
