import { API_BASE } from '@/lib/base';
import { RunSpendPanel } from '@/components/RunSpendPanel';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { useStore } from '@/lib/store';
import { useT } from '@/lib/prefs';
import { NeedProject } from '@/components/NeedProject';
import { ExecutionCompare } from '@/components/workbench/ExecutionCompare';
import { RunReportPanel } from '@/components/workbench/RunReportPanel';
import { RegressionCandidates } from '@/components/workbench/RegressionCandidates';
import { TextCaseDetail } from '@/components/workbench/TextCaseDetail';
import { Button } from '@/components/ui';
import { WorkflowError, workflowRequestId, workflowBase, workflowHref, workflowRequest as request, type WorkflowRun, type ReviewCase, type Revision, type Execution } from '@/lib/workflowRuns';
const field = 'mt-1 w-full rounded border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary';
const stages = ['instructions', 'modules', 'stories', 'cases', 'gate', 'finalize', 'review', 'g2', 'execution'];
const short = (s: string) => s.length > 24 ? `${s.slice(0, 12)}…${s.slice(-6)}` : s;
function State({ value }: { value: string }) { const t = useT(); return <span className={`rounded border px-2 py-1 font-mono text-xs ${['done', 'passed', 'completed', 'approved'].includes(value) ? 'border-ok/30 text-ok' : ['failed', 'infra_error', 'blocked', 'rejected'].includes(value) ? 'border-bad/30 text-bad' : 'border-border text-muted-foreground'}`}>{t(`workflow.status.${value}`)}</span>; }
function MaterialForm({ projectId, onCreated }: { projectId: string; onCreated: (id: string) => void }) {
  const t = useT(), [text, setText] = useState(''), [name, setName] = useState('requirements.md'), [limit, setLimit] = useState(12), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const intent = useRef<{ hash: string; key: string }>();
  async function start(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const input = { materials: [{ name, text }], limit }; const hash = JSON.stringify(input); if (intent.current?.hash !== hash) intent.current = { hash, key: workflowRequestId() }; try { const run = await request<{ wfRunId: string }>(workflowBase(projectId), { ...input, idempotencyKey: intent.current.key }); onCreated(run.wfRunId); } catch (e) { setError(e instanceof WorkflowError ? (e.detail ?? e.code) : 'request_failed'); } finally { setBusy(false); } }
  return <form onSubmit={start} className="space-y-4 rounded-lg border border-border bg-card p-5">
    <h3 className="font-semibold">{t('workflow.new')}</h3><p className="text-sm text-muted-foreground">{t('workflow.createHelp')} <a className="underline" href="#/?open=settings&s=models">{t('modelRoles.title')}</a></p>
    <div className="grid gap-4 sm:grid-cols-[1fr_130px]"><label className="text-xs">{t('workflow.materialName')}<input required className={field} value={name} onChange={e => setName(e.target.value)} /></label><label className="text-xs">{t('workflow.limit')}<input type="number" min={1} max={50} className={field} value={limit} onChange={e => setLimit(Number(e.target.value))} /></label></div>
    <label className="block text-xs">{t('workflow.requirements')}<textarea required rows={8} className={field} value={text} onChange={e => setText(e.target.value)} placeholder={t('workflow.requirementsHint')} /></label>
    {error && <p role="alert" className="text-sm text-bad">{t('workflow.requestFailed')} <code>{error}</code></p>}
    <Button type="submit" variant="primary" disabled={busy}>{t(busy ? 'workflow.starting' : 'workflow.start')}</Button>
  </form>;
}
export function CaseEditor({ item, onSave, disabled }: { item: ReviewCase; onSave: (content: ReviewCase['content']) => void; disabled: boolean }) {
  const t = useT(), [steps, setSteps] = useState(item.content.steps.join('\n')), [expected, setExpected] = useState(item.content.expected), [oracle, setOracle] = useState(item.content.oracle ? JSON.stringify(item.content.oracle, null, 2) : ''), [error, setError] = useState(false);
  const originalReadiness = item.content.readiness as {design?: string; execution?: string; reason?: string; requirements?: unknown[]} | undefined;
  const [readiness,setReadiness]=useState(originalReadiness?.execution??''),[reason,setReason]=useState(originalReadiness?.reason??'');
  return <form onSubmit={e => { e.preventDefault(); try { const content = { ...item.content, ...(readiness?{readiness:{...originalReadiness,design:originalReadiness?.design??'candidate',execution:readiness,reason}}:{}), steps: steps.split('\n').filter(s => s.trim()), expected, oracle: oracle.trim() ? JSON.parse(oracle) : undefined }; setError(false); onSave(content); } catch { setError(true); } }} className="mt-3 space-y-3">
    <label className="block text-xs">{t('workflow.steps')}<textarea required className={field} rows={4} value={steps} onChange={e => setSteps(e.target.value)} /></label>
    <label className="block text-xs">{t('workflow.expected')}<textarea required className={field} rows={3} value={expected} onChange={e => setExpected(e.target.value)} /></label>
    <label className="block text-xs">{t('workflow.oracle')}<textarea className={`${field} font-mono`} rows={4} value={oracle} onChange={e => setOracle(e.target.value)} /></label>
    <fieldset className="rounded border border-border p-3 space-y-3"><legend className="text-sm">{t('workflow.readinessEdit')}</legend>
      <p className="text-xs text-muted-foreground">{t('workflow.readinessEditHint')}</p>
      <label className="block text-xs">{t('workflow.executionReadiness')}<select className={field} value={readiness} onChange={e=>setReadiness(e.target.value)}><option value="">—</option>{['ready','requires-fixture','requires-session','blocked','not-executable'].map(v=><option key={v} value={v}>{t(`workflow.readiness.${v}`)}</option>)}</select></label>
      <label className="block text-xs">{t('workflow.readinessReason')}<textarea className={field} rows={3} value={reason} onChange={e=>setReason(e.target.value)} required={!!readiness}/></label>
    </fieldset>
    <p className="text-xs text-muted-foreground">{t('workflow.newRevisionHelp')}</p>{error && <p role="alert" className="text-bad">{t('workflow.invalidJson')}</p>}<Button type="submit" disabled={disabled}>{t('workflow.saveRevision')}</Button>
  </form>;
}
function ArtifactViewer({ projectId, revision, all, onSelect }: { projectId: string; revision: Revision; all: Revision[]; onSelect: (r: Revision) => void }) {
  const t = useT(), [content, setContent] = useState<unknown>(), [error, setError] = useState(false), [parent, setParent] = useState<unknown>();
  useEffect(() => { const c = new AbortController(); setContent(undefined); setParent(undefined); setError(false); const base = workflowBase(projectId); const read = (r: Revision) => request<{ content: unknown }>(`${base}/${r.runId}/artifacts/${r.id}`, undefined, 'GET', c.signal); void (async () => { try { const prior = all.find(r => r.id === revision.parentRevision); const [value, old] = await Promise.all([read(revision), prior ? read(prior) : Promise.resolve(null)]); setContent(value.content); setParent(old?.content); } catch { if (!c.signal.aborted) setError(true); } })(); return () => c.abort(); }, [projectId, revision.id, revision.runId, revision.parentRevision, all]);
  const show = (v: unknown) => typeof v === 'string' ? v : JSON.stringify(v, null, 2);
  function download() { const a = document.createElement('a'); a.href = `${API_BASE}/api/${workflowBase(projectId)}/${revision.runId}/artifacts/${revision.id}/export`; a.download = `${revision.kind}-v${revision.revision}.json`; a.click(); }
  return <section className="min-w-0 space-y-3 rounded-md border border-border bg-card p-4" aria-label={t('workflow.artifactDetail')}>
    <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="break-all font-medium">{revision.name} · v{revision.revision}</h4><Button disabled={content === undefined} onClick={download}>{t('workflow.download')}</Button></div>
    <p className="break-all font-mono text-xs text-muted-foreground">SHA256 {revision.contentHash}</p>
    <div className="flex flex-wrap items-center gap-2 text-xs"><span>{t('workflow.sources')}</span>{revision.sourceRefs.map(id => { const source = all.find(r => r.id === id); return source ? <Button key={id} size="sm" onClick={() => onSelect(source)}>{source.name} · v{source.revision}</Button> : <span key={id} className="break-all">{id}</span>; })}</div>
    {error ? <p role="alert" className="text-bad">{t('workflow.artifactFailed')}</p> : content === undefined ? <p>{t('workflow.loading')}</p> : <div className={`grid min-w-0 gap-4 ${parent !== undefined ? 'xl:grid-cols-2' : ''}`}>
      {parent !== undefined && <div className="min-w-0"><h5 className="mb-2 text-xs text-muted-foreground">{t('workflow.previous')}</h5><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all rounded bg-muted p-3 text-xs">{show(parent)}</pre></div>}
      <div className="min-w-0"><h5 className="mb-2 text-xs text-muted-foreground">{t('workflow.current')}</h5><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all rounded bg-muted p-3 text-xs">{show(content)}</pre></div>
    </div>}
  </section>;
}
export function RunDetail({ projectId, run, refresh }: { projectId: string; run: WorkflowRun; refresh: () => void }) {
  const t = useT(), base = `${workflowBase(projectId)}/${run.id}`;
  const [cases, setCases] = useState<ReviewCase[]>([]), [executions, setExecutions] = useState<Execution[]>([]), [selected, setSelected] = useState<Set<string>>(new Set()), [artifactId, setArtifactId] = useState(new URLSearchParams(location.hash.split('?')[1] ?? '').get('artifact') ?? ''), [kind, setKind] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [editing, setEditing] = useState('');
  const [compiledReady,setCompiledReady]=useState(false);
  const [reviewHistory,setReviewHistory]=useState<unknown[]>([]);
  const [rejectReason,setRejectReason]=useState('');
  const finalized = run.nodes.some(n => n.node === 'finalize' && ['done', 'waiting_review'].includes(n.phase));
  useEffect(() => { if (run.provenance !== 'registered') return; const c = new AbortController(); void Promise.all([finalized ? request<{ cases: ReviewCase[]; compiled?: {ready:boolean} }>(`${base}/review`, undefined, 'GET', c.signal) : Promise.resolve({ cases: [], compiled: {ready:false} }), request<{ executions: Execution[] }>(`${base}/executions`, undefined, 'GET', c.signal)]).then(([a, b]) => { setCases(a.cases); setCompiledReady(a.compiled?.ready===true); setExecutions(b.executions); }).catch(e => { if (!c.signal.aborted) setError(e instanceof WorkflowError ? e.code : 'request_failed'); }); return () => c.abort(); }, [base, finalized, run]);
  const executionIntent = useRef<string>();
  async function action(path: string, body: unknown = {}, method = 'POST') { if (busy) return; setBusy(true); setError(''); setMessage(''); try { if (path === 'stages/execute') { executionIntent.current ??= workflowRequestId(); body = { ...(body as object), idempotencyKey: executionIntent.current }; } const result = await request<Record<string, unknown>>(`${base}/${path}`, body, method); if (path === 'stages/execute') executionIntent.current = undefined; if (Array.isArray(result.results) && result.results.some(r => r.status === 'conflict')) setMessage(t('workflow.someConflicts')); else if (result.continuation) setMessage(t('workflow.continueHost')); else setMessage(t('workflow.saved')); if (result.revision) setArtifactId((result.revision as Revision).id); setSelected(new Set()); setEditing(''); refresh(); } catch (e) { setError(e instanceof WorkflowError ? (e.detail ?? e.code) : 'request_failed'); } finally { setBusy(false); } }
  const chosen = cases.filter(c => selected.has(c.caseId)); const approved = cases.filter(c => c.approval?.decision === 'approved');
  const artifact = run.revisions.find(r => r.id === artifactId); const code = [...run.revisions].reverse().find(r => r.kind === 'code');
  const resumable = ['paused', 'cancelled', 'interrupted', 'failed', 'infra_error', 'budget_exhausted'].includes(run.status);
  return <article className="min-w-0 space-y-5">
    <header className="space-y-4 border-b border-border pb-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="break-all font-mono text-base">{short(run.id)}</h2><State value={run.status} /></div>
      <dl className="grid gap-3 text-xs sm:grid-cols-3"><div><dt className="text-muted-foreground">{t('workflow.entry')}</dt><dd className="mt-1">{run.binding?.models.entry === 'host' ? run.binding.models.runtime : run.binding ? 'Web' : t('workflow.unknown')}</dd></div><div><dt className="text-muted-foreground">{t('modelRoles.planner')}</dt><dd className="mt-1 break-all">{run.binding?.models.planner.model ?? t('workflow.hostUnknown')}</dd></div><div><dt className="text-muted-foreground">{t('modelRoles.executor')}</dt><dd className="mt-1 break-all">{run.binding?.models.executor.model ?? t('workflow.unknown')}</dd></div></dl>
      <p className="break-all font-mono text-xs text-muted-foreground">{t('workflow.skillVersion')} {run.binding?.skillVersion ?? t('workflow.unknown')} · {t('workflow.input')} {run.binding?.inputHash ? short(run.binding.inputHash) : t('workflow.unknown')}</p>
    </header>
    {run.provenance !== 'registered' ? <p className="rounded border border-border p-4 text-sm">{t('workflow.legacy')}</p> : <>
      <ol className="grid gap-2 sm:grid-cols-4" aria-label={t('workflow.progress')}>{stages.map((stage, i) => { const node = run.nodes.find(n => n.node === stage); const state = stage === 'finalize' && finalized ? 'done' : stage === 'review' ? (cases.length && cases.every(c => c.approval) ? 'done' : finalized ? 'waiting_review' : 'queued') : stage === 'g2' ? (code ? compiledReady ? 'done' : 'blocked' : 'queued') : node?.phase ?? 'queued'; return <li key={stage} className="rounded border border-border p-3"><div className="mb-2 flex items-center gap-2 text-sm"><span className="font-mono text-xs text-muted-foreground">{String(i + 1).padStart(2, '0')}</span>{t(`workflow.stage.${stage}`)}</div><State value={state} />{node?.message && <p className="mt-2 break-words text-xs text-bad">{node.message}</p>}</li>; })}</ol>
      <RunSpendPanel projectId={projectId} runId={run.id} status={run.status} />
      <RunReportPanel projectId={projectId} runId={run.id} status={run.status} />
      <details onToggle={e=>{if(e.currentTarget.open)void request<{events:unknown[]}>(`${base}/review-history`).then(r=>setReviewHistory(r.events)).catch(()=>setReviewHistory([]))}}><summary className="cursor-pointer text-sm">{t('workflow.review')} · {t('workflow.previous')}</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(reviewHistory,null,2)}</pre></details>
      <div className="flex flex-wrap items-center gap-2">{resumable ? <Button disabled={busy} onClick={() => void action('resume')}>{t('workflow.resume')}</Button> : !['completed', 'cancelled'].includes(run.status) && <Button disabled={busy} onClick={() => void action('cancel')}>{t('workflow.cancel')}</Button>}<Button onClick={refresh} disabled={busy}>{t('workflow.refresh')}</Button></div>
      {finalized && <section className="space-y-3" aria-label={t('workflow.review')}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{t('workflow.review')} <span className="font-mono text-muted-foreground">{approved.length}/{cases.length}</span></h3><div className="flex flex-wrap gap-2"><Button disabled={busy || !chosen.length} onClick={() => void action('review', { items: chosen.map(c => ({ caseId: c.caseId, revisionId: c.revision.id, decision: 'approved' })) })}>{t('workflow.approveSelected')}</Button><Button disabled={busy || !chosen.length || rejectReason.trim().length < 4} title={rejectReason.trim().length < 4 ? t('review.rejectReasonHint') : undefined} onClick={() => void action('review', { items: chosen.map(c => ({ caseId: c.caseId, revisionId: c.revision.id, decision: 'rejected' })), note: rejectReason })}>{t('workflow.rejectSelected')}</Button></div></div>
        <label className="block text-xs">{t('review.rejectReason')}<input className="mt-1 w-full rounded border border-border bg-background px-3 py-2 text-sm" placeholder={t('review.rejectReasonPlaceholder')} value={rejectReason} onChange={e => setRejectReason(e.target.value)} /></label>
        <p className="-mt-1 text-xs text-muted-foreground">{t('review.rejectReasonHint')}</p>
        <label className="flex min-h-8 items-center gap-2 text-xs"><input type="checkbox" checked={cases.length > 0 && chosen.length === cases.length} onChange={e => setSelected(e.target.checked ? new Set(cases.map(c => c.caseId)) : new Set())} />{t('workflow.selectAll')}</label>
        {cases.map(c => <section key={c.caseId} className="rounded-md border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex min-w-0 items-center gap-3 font-medium"><input type="checkbox" checked={selected.has(c.caseId)} onChange={e => setSelected(prev => { const next = new Set(prev); e.target.checked ? next.add(c.caseId) : next.delete(c.caseId); return next; })} /><span className="break-words">{c.content.title}</span></label><div className="flex items-center gap-2"><span className="font-mono text-xs text-muted-foreground">v{c.revision.revision}</span><State value={c.approval?.decision ?? 'waiting_review'} /></div></div>
          <ol className="ml-7 mt-3 list-decimal space-y-1 text-sm">{c.content.steps.map((s, i) => <li key={i}>{s}</li>)}</ol><p className="mt-3 text-sm"><span className="text-muted-foreground">{t('workflow.expected')} · </span>{c.content.expected}</p>
          <details className="mt-3 text-xs"><summary className="cursor-pointer">{t('caseDetail.full')}</summary><div className="mt-3 text-sm"><TextCaseDetail kase={c.content} /></div></details>
          {c.approval && <p className="mt-3 text-xs text-muted-foreground">{c.approval.principal.id} · {new Date(c.approval.at).toLocaleString()}</p>}
          <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => setArtifactId(c.revision.id)}>{t('workflow.lineage')}</Button><Button size="sm" disabled={busy} onClick={() => setEditing(editing === c.caseId ? '' : c.caseId)}>{t('workflow.edit')}</Button></div>
          {editing === c.caseId && <CaseEditor key={c.revision.id} item={c} disabled={busy} onSave={content => void action('review', { caseId: c.caseId, expectedRevision: c.revision.id, content }, 'PATCH')} />}
        </section>)}
        <div className="flex flex-wrap gap-3 border-t border-border pt-4"><Button variant="primary" disabled={busy || !approved.length} onClick={() => void action('preparation/start', { revisionIds: approved.map(c => c.revision.id) })}>{t('workflow.compile')}</Button>{code && <Button disabled={busy || resumable || !compiledReady || run.status === 'executing'} onClick={() => void action('stages/execute', { codeRevision: code.id, idempotencyKey: 'assigned-by-action' })}>{t('workflow.execute')}</Button>}</div>
      </section>}
      {executions.length > 0 && <section className="space-y-3"><h3 className="font-semibold">{t('workflow.executions')}</h3>{executions.map(e => <div key={e.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-border p-3 text-xs"><span className="font-mono">{short(e.id)}</span><State value={e.status} />{e.resultRevision && <Button onClick={() => setArtifactId(e.resultRevision!)}>{t('workflow.evidence')}</Button>}</div>)}
        {/* 一次执行只看自己看不出东西：同样的通过数，失败的可能是完全不同的几条。 */}
        <ExecutionCompare projectId={projectId} runId={run.id} executionId={executions[executions.length - 1]?.id} />
      </section>}
      {(executions.length > 0 || finalized) && <RegressionCandidates key={`${run.id}-${executions.length}-${run.status}`} projectId={projectId} runId={run.id} hasExecutions={executions.length > 0} />}
    </>}
    {error && <p role="alert" className="rounded border border-bad/30 p-3 text-sm text-bad">{t('workflow.requestFailed')} <code className="break-all">{error}</code></p>}{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}
    <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{t('workflow.artifacts')} <span className="font-mono text-muted-foreground">{run.revisions.length}</span></h3><label className="text-xs">{t('workflow.type')} <select className="rounded border border-border bg-background px-2 py-1" value={kind} onChange={e => setKind(e.target.value)}><option value="">{t('workflow.allTypes')}</option>{[...new Set(run.revisions.map(r => r.kind))].map(k => <option key={k} value={k}>{t(`workflow.kind.${k}`)}</option>)}</select></label></div>
      <div className="max-h-64 overflow-auto rounded border border-border">{run.revisions.filter(r => !kind || r.kind === kind).map(r => <button key={r.id} onClick={() => setArtifactId(r.id)} className={`flex w-full items-center justify-between gap-3 border-b border-border px-3 py-3 text-left text-xs last:border-b-0 hover:bg-muted focus-visible:ring-2 focus-visible:ring-primary ${r.id === artifactId ? 'bg-muted' : ''}`}><span className="min-w-0 break-all">{r.name}</span><span className="shrink-0 font-mono text-muted-foreground">v{r.revision}</span></button>)}</div>
      {artifact && <ArtifactViewer projectId={projectId} revision={artifact} all={run.revisions} onSelect={r => setArtifactId(r.id)} />}
    </section>
  </article>;
}
function ProjectWorkflows({ projectId, focusRun }: { projectId: string; focusRun?: string }) {
  const t = useT(), [runs, setRuns] = useState<WorkflowRun[]>([]), [selectedId, setSelectedId] = useState(focusRun ?? ''), [creating, setCreating] = useState(false), [error, setError] = useState(false), [loaded, setLoaded] = useState(false), [reload, setReload] = useState(0);
  const refresh = useCallback(() => setReload(n => n + 1), []);
  useEffect(() => { if (focusRun) { setSelectedId(focusRun); setCreating(false); } }, [focusRun]);
  useEffect(() => { const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; async function poll() { try { const data = await request<{ runs: WorkflowRun[] }>(workflowBase(projectId), undefined, 'GET', controller.signal); if (!controller.signal.aborted) { setRuns(data.runs); setError(false); setLoaded(true); } } catch { if (!controller.signal.aborted) { setError(true); setLoaded(true); } } if (!controller.signal.aborted) timer = setTimeout(() => void poll(), 4000); } void poll(); return () => { controller.abort(); clearTimeout(timer); }; }, [projectId, reload]);
  function choose(id: string) { setSelectedId(id); setCreating(false); location.hash = workflowHref(id); }
  const selected = runs.find(r => r.id === selectedId) ?? (!selectedId ? runs[0] : undefined);
  return <main className="mx-auto w-full max-w-[1500px] p-4 md:p-7"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 font-mono text-[11px] tracking-[0.16em] text-muted-foreground">TESTPILOT / WORKFLOWS</p><h1 className="text-2xl font-semibold tracking-tight">{t('workflow.title')}</h1><p className="mt-2 text-sm text-muted-foreground">{t('workflow.subtitle')}</p></div><Button variant="primary" onClick={() => setCreating(true)}>{t('workflow.new')}</Button></header>
    {error && <p role="alert" className="mb-4 rounded border border-bad/30 p-3 text-sm text-bad">{t('workflow.connectionError')} <Button onClick={refresh}>{t('workflow.refresh')}</Button></p>}
    {!loaded && <p role="status">{t('workflow.loading')}</p>}
    <div className="grid items-start gap-6 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="min-w-0 rounded-lg border border-border bg-card" aria-label={t('workflow.runList')}><div className="border-b border-border px-4 py-3 text-xs text-muted-foreground">{t('workflow.runList')} · {runs.length}</div><div className="max-h-[65vh] overflow-auto">{!runs.length && loaded && <p className="p-5 text-sm text-muted-foreground">{t('workflow.empty')}</p>}{runs.map(r => <button key={r.id} onClick={() => choose(r.id)} className={`block w-full space-y-2 border-b border-border p-4 text-left last:border-b-0 hover:bg-muted focus-visible:ring-2 focus-visible:ring-primary ${selected?.id === r.id && !creating ? 'border-l-2 border-l-primary bg-muted/40' : ''}`}><span className="block truncate font-mono text-xs">{short(r.id)}</span><State value={r.status} /><span className="block text-xs text-muted-foreground">{r.binding?.models.entry === 'host' ? r.binding.models.runtime : r.binding ? 'Web' : t('workflow.unknown')} · {r.startedAt ? new Date(r.startedAt).toLocaleString() : '—'}</span></button>)}</div></aside>
      <div className="min-w-0">{creating || (loaded && !runs.length) ? <MaterialForm projectId={projectId} onCreated={id => { choose(id); refresh(); }} /> : selected ? <RunDetail key={selected.id} projectId={projectId} run={selected} refresh={refresh} /> : loaded ? <p className="p-5 text-sm text-muted-foreground">{t('workflow.runMissing')}</p> : null}</div>
    </div>
  </main>;
}
export function WorkflowRunsPage({ focusRun }: { focusRun?: string }) { const projectId = useStore(s => s.activeProjectId); return <div className="min-w-0 flex-1 overflow-auto">{projectId ? <ProjectWorkflows key={projectId} projectId={projectId} focusRun={focusRun} /> : <NeedProject />}</div>; }
