import {describe,it,expect} from 'vitest';
import {summarize,validatePlan,type Task,type Trial} from '../src/evidenceStudy/contracts.js';
const task:Task={id:'dialog',split:'dev',family:'visibility',title:'Dialog',buttons:['Open','Close'],initial:'Closed',intermediate:'Open',final:'Closed'};
function outcomes():Trial[]{return (['baseline','candidate'] as const).flatMap(arm=>(['healthy','intermediate','final'] as const).flatMap(variant=>[0,1,2].map(repeat=>({taskId:'dialog',split:'dev',family:'visibility',arm,variant,repeat,status:variant==='healthy'||(arm==='baseline'&&variant==='intermediate')?'passed':'failed',ms:1,actions:1,evidence:'x.png'} as Trial))));}
describe('evidence admission, not a cosmetic success counter',()=>{
 it('requires stable defect detection with passing healthy controls',()=>{const r=summarize(outcomes(),[task]);expect(r.decision).toBe('bounded-improvement');expect(r.baseline.stableKills).toBe(1);expect(r.candidate.stableKills).toBe(2);expect(r.taskVariants).toBe(1);});
 it('does not count infrastructure failures as defect detection',()=>{const rows=outcomes();rows.find(r=>r.arm==='candidate'&&r.variant==='intermediate')!.status='unobservable';const r=summarize(rows,[task]);expect(r.decision).toBe('insufficient-evidence');expect(r.candidate.stableKills).toBe(1);});
 it('rejects a candidate that cries wolf on a healthy screen',()=>{const rows=outcomes();rows.find(r=>r.arm==='candidate'&&r.variant==='healthy')!.status='failed';expect(summarize(rows,[task]).decision).toBe('insufficient-evidence');});
 it('rejects missing and duplicated runs instead of improving a denominator',()=>{const rows=outcomes();rows.pop();expect(summarize(rows,[task]).complete).toBe(false);rows.push({...rows[0]});expect(summarize(rows,[task]).complete).toBe(false);});
 it('rejects intermittent defect kills',()=>{const rows=outcomes();rows.find(r=>r.arm==='candidate'&&r.variant==='intermediate')!.status='passed';const r=summarize(rows,[task]);expect(r.candidate.unstable).toBe(1);expect(r.decision).toBe('insufficient-evidence');});
 it('cannot repair model-generated actions or silently replace expected outcomes',()=>{const p={id:'dialog',title:'Dialog',steps:[{text:'Click Open'},{text:'Click Close'}],expected:'Closed',oracle:{kind:'text',value:'Closed'},assertions:[{statement:'Open',afterStep:1,oracle:{kind:'text',value:'Open'}}]};expect(validatePlan(p,task)).toEqual(p);expect(()=>validatePlan({...p,oracle:{kind:'text',value:'Open'}},task)).toThrow('generation_contract_mismatch');expect(()=>validatePlan({...p,assertions:[]},task)).toThrow();});
});
