import{afterAll,expect,it}from'vitest';import{mkdtempSync,mkdirSync,writeFileSync,rmSync}from'node:fs';import{join}from'node:path';import{tmpdir}from'node:os';
import{EvolutionStore,digest,type Score}from'../src/evolution/store.js';import{createGates}from'../src/evolution/releaseGates.js';import{RunLedger,contentHash}from'../src/runLedger.js';import{canonicalJSON}from'@testpilot/harness-core/run-contracts';import{saveGold,freezeGold}from'../src/gold.js';import{captureWebModels}from'./helpers/model-snapshot.js';
const root=mkdtempSync(join(tmpdir(),'tp-release-gates-')),data=join(root,'ledger'),state=new EvolutionStore(join(root,'evaluation')),ledger=new RunLedger(join(data,'workflows.db'),join(data,'revision-blobs'));afterAll(()=>{ledger.close();state.close();rmSync(root,{recursive:true,force:true});});
const h=(memory:'scoped'|'off')=>digest({memory});const score=(value:number,memory:'scoped'|'off'):Score=>({policyHash:h(memory),score:value,p0Failures:0,unobservable:0,n:3,binding:{inputHash:'a'.repeat(64),datasetHash:'b'.repeat(64),rubricHash:'c'.repeat(64),runtime:'fixture',model:'fake',replicates:3},source:'SYNTHETIC fixtures'});
ledger.db.exec('CREATE TABLE run_stage_receipts(runId TEXT,stage TEXT,revisionId TEXT);CREATE TABLE workflow_executions(runId TEXT,status TEXT,resultRevision TEXT,codeRevision TEXT,startedAt TEXT)');
function run(runtime:'codex'|'claude-code'|'penguin',memory:'off'|'scoped',i:number){const id=`${runtime}-${memory}-${i}`,policy={memory},context={enabled:memory==='scoped',entries:[],policy:'fixture'},memoryDigest=contentHash(canonicalJSON(context)),models=captureWebModels().binding;models.runtime=runtime;
 ledger.register({id,projectId:'p',externalId:id,idempotencyKey:id,binding:{schemaVersion:1,models,skillVersion:'fixture',loadedDigest:'d'.repeat(64),agentVersion:`fixture-${memory}`,contextPolicy:policy,memoryDigest,materialsHash:'a'.repeat(64),inputHash:'b'.repeat(64),environmentHash:null,materialRevisions:[]}},{kind:'system',id:'fixture'});
 const actor={kind:'system' as const,id:'stage-validator'};const artifact=(name:string,kind:any,content:unknown,by=actor)=>ledger.putRevision({runId:id,projectId:'p',name,kind,content},by);const stage=(name:string,kind:any,content:unknown)=>{const r=artifact(name,kind,content);ledger.db.prepare('INSERT INTO run_stage_receipts VALUES (?,?,?)').run(id,name,r.id);return r;};
 stage('instructions','report',{loadedDigest:'d'.repeat(64),memory:{...context,digest:memoryDigest}});const cases=[{id:'c1',title:'Count increments',steps:['Click increment'],expected:'Count equals 1'}];stage('cases','cases',{cases});stage('finalize','report',{});const code=artifact('g2','code',{cases});const execution=artifact('exec','execution',{status:'passed',codeRevision:code.id,results:[{caseId:'c1',status:'passed'}]},{kind:'system',id:'workflow-executor'});ledger.db.prepare('INSERT INTO workflow_executions VALUES (?,?,?,?,?)').run(id,'passed',execution.id,code.id,new Date().toISOString());return{dataDir:data,projectId:'p',runId:id};}
it('scores only hash-verified, policy-bound unique workflow runs against actually frozen gold; rejects missing review and duplicate replication',async()=>{
 const c=state.create({synthetic:true});state.proposal(c.id,{memory:'off'});state.recordDevelopment(c.id,score(.5,'scoped'),score(1,'off'));
 const hosts=Object.fromEntries((['codex','claude-code','penguin'] as const).map(runtime=>[runtime,{baseline:[1,2,3].map(i=>run(runtime,'scoped',i)),candidate:[1,2,3].map(i=>run(runtime,'off',i))}]));const manifest={schemaVersion:1,capability:'synthetic',candidates:{[c.id]:{heldout:hosts.codex,hosts}}},path=join(root,'manifest.json');writeFileSync(path,JSON.stringify(manifest));mkdirSync(join(root,'benchmark/synthetic'),{recursive:true});
 const gates=createGates({store:state,repoRoot:root,manifestPath:path});await expect(gates.heldout!(c.id)).rejects.toThrow('human_frozen_gold_required');
 const item=(id:string,heldOut:boolean)=>({id,title:'Count increments',ruleFamily:id,split:heldOut?'heldout' as const:'train' as const,heldOut,expected:'Count equals 1',sourceRefs:['statement/counter.md'],match:{anyOf:['increment'],assertAnyOf:['Count equals 1']}});
 saveGold('synthetic',{id:'synthetic',reviewPolicy:'individual-v1',items:[item('train',false),item('held',true)]},{root,actor:{kind:'human',id:'SYNTHETIC-REVIEWER'},reviewedItemIds:['train','held']});freezeGold('synthetic',root);
 const result=await gates.heldout!(c.id);expect(result.baseline.score).toBe(1);expect(result.candidate.policyHash).toBe(h('off'));expect(JSON.stringify(result)).not.toContain('Count equals 1');expect((await gates.hostRegression!(c.id)).passed).toBe(true);
 manifest.candidates[c.id].heldout.baseline[1]=manifest.candidates[c.id].heldout.baseline[0];writeFileSync(path,JSON.stringify(manifest));await expect(gates.heldout!(c.id)).rejects.toThrow('release_duplicate_run');
});
