import {afterEach,expect,it} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';
import{EvolutionStore,digest,type Score}from'../src/evolution/store.js';
import{isolatedChat}from'../src/evolution/sandbox.js';
import{createServer}from'node:http';import{once}from'node:events';import type{AddressInfo}from'node:net';
const dirs:string[]=[],stores:EvolutionStore[]=[];afterEach(()=>{stores.splice(0).forEach(s=>s.close());dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
function setup(){const dir=mkdtempSync(join(tmpdir(),'tp-evolution-'));dirs.push(dir);const store=new EvolutionStore(dir);stores.push(store);return store;}
const score=(n:number,extra:Partial<Score>={}):Score=>({policyHash:digest({memory:'scoped'}),score:n,p0Failures:0,unobservable:0,n:3,binding:{inputHash:'a'.repeat(64),datasetHash:'b'.repeat(64),rubricHash:'c'.repeat(64),runtime:'synthetic-unit-fixture',model:'fake',replicates:3},source:'SYNTHETIC test fixture, not human or product evidence',...extra});
function improved(s:EvolutionStore){const c=s.create({synthetic:true});s.proposal(c.id,{memory:'off'});return s.recordDevelopment(c.id,score(.5),score(1,{policyHash:digest({memory:'off'})}));}
it('rejects a same-score candidate, missing binding and P0 regression; never auto-promotes a higher score',()=>{const s=setup(),a=s.active();let c=s.create({});expect(s.recordDevelopment(c.id,score(1),score(1)).reason).toBe('no_strict_improvement');c=s.create({});expect(s.recordDevelopment(c.id,score(.5),score(1,{binding:{...score(1).binding,inputHash:''}})).reason).toBe('incomparable_binding');c=s.create({});expect(s.recordDevelopment(c.id,score(.5),score(1,{p0Failures:1})).reason).toBe('p0_regression');c=improved(s);expect(c.status).toBe('awaiting_review');expect(s.active()).toEqual(a);expect(()=>s.promote(c.id,0,'test-reviewer')).toThrow('heldout_required');expect(()=>s.proposal(c.id,{memory:'off',oracle:'modified'})).toThrow();});
it('requires held-out results and bound host regression, enforces one held-out attempt, supports CAS promotion/rollback without changing old versions',()=>{const s=setup(),a=s.active(),c=improved(s);s.beginHeldout(c.id);expect(()=>s.beginHeldout(c.id)).toThrow('heldout_attempt_limit');s.recordHeldout(c.id,score(1),score(.5,{policyHash:c.policyHash}));s.recordHostRegression(c.id,true,c.policyHash,'synthetic-three-host-fixture');expect(()=>s.promote(c.id,0,'test-reviewer')).toThrow('heldout_regression');
 const d=improved(s);s.beginHeldout(d.id);s.recordHeldout(d.id,score(1),score(1,{policyHash:d.policyHash}));s.recordHostRegression(d.id,true,d.policyHash,'synthetic-three-host-fixture');expect(()=>s.promote(d.id,0,'')).toThrow('human_reviewer_required');const p=s.promote(d.id,0,'synthetic-test-reviewer');expect(p.policy.memory).toBe('off');expect(p.generation).toBe(1);expect(()=>s.rollback(a.version,0,'test-reviewer')).toThrow('active_version_conflict');expect(s.rollback(a.version,1,'synthetic-test-reviewer').policy.memory).toBe('scoped');expect(s.history().filter(h=>h.action==='promote')).toHaveLength(1);
});
it.runIf(process.platform==='darwin')('OS-denies private answers while the isolated worker makes an actual scoped proxy request',async()=>{const s=setup();const server=createServer(async(req,res)=>{const parts=[];for await(const p of req)parts.push(p);const body=JSON.parse(Buffer.concat(parts).toString());expect(JSON.stringify(body)).not.toContain('private evaluation canary');res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:'{"memory":"off"}'},finish_reason:'stop'}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));});server.listen(0,'127.0.0.1');await once(server,'listening');try{const r=await isolatedChat({privateRoot:s.root,repoRoot:resolve(import.meta.dirname,'../..'),connection:{role:'planner',endpoint:`http://127.0.0.1:${(server.address() as AddressInfo).port}/v1`,apiKey:'temporary-proxy-fixture',model:'synthetic',thinking:false},request:{stable:'Return policy',variable:'development feedback only',maxTokens:128},timeoutMs:20000});expect(r.isolation.reads.every((p:any)=>p.denied)).toBe(true);expect(r.isolation.writes.every((p:any)=>p.denied)).toBe(true);expect(JSON.parse(r.response.text)).toEqual({memory:'off'});}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}},25000);
it('treats invalid or truncated model output as unobservable rather than a P0 regression',async()=>{const{scorePlan}=await import('../src/evolution/scorePlan.js');expect(scorePlan({invalidResponse:true,truncated:true})).toMatchObject({valid:false,p0Failure:false,unobservable:true,passed:false});expect(scorePlan({selector:'#count',valueType:'number',missingEvidence:'failed',expectedAfterIncrement:1})).toMatchObject({valid:true,p0Failure:true,unobservable:false,passed:false});});
it('prepares a candidate in a fresh lab without activating it in the source evaluator',async()=>{const s=setup(),before=s.active(),c=improved(s);const{prepareCandidateInstance}=await import('../src/evolution/candidateInstance.js');const lab=prepareCandidateInstance(c);dirs.push(lab.workspace);expect(lab.active.policy.memory).toBe('off');expect(lab.active.evaluationOnly).toBe(true);expect(s.active()).toEqual(before);expect(lab.env.TP_EVOLUTION_DIR).not.toBe(s.root);});
