import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {captureWebModels} from './helpers/model-snapshot.js';
const chat=vi.hoisted(()=>vi.fn());vi.mock('../src/plannerHost.js',()=>({savedHost:()=> 'codex',requireHost:async()=> 'codex',nativeHostChat:chat}));
vi.mock('../src/modelSnapshots.js',async()=>({captureHostWebModels:(await import('./helpers/model-snapshot.js')).captureHostWebModels}));
let dir:string,project:string,other:string,runId:string,ref:string,snapshot:string,discovery:string,service:typeof import('../src/runService.js'),database:typeof import('../src/db.js'),assets:import('../src/projectAssets.js').ProjectAssets,tasks:import('../src/projectTasks.js').ProjectTasks,discoveries:import('../src/projectDiscoveries.js').ProjectDiscoveries,incremental:typeof import('../src/projectIncremental.js');
const human={kind:'human' as const,id:'reviewer'},system={kind:'system' as const,id:'fixture'};
beforeAll(async()=>{dir=mkdtempSync(join(tmpdir(),'tp-evolution-'));vi.stubEnv('TP_DATA_DIR',dir);database=await import('../src/db.js');service=await import('../src/runService.js');project=database.createProject('Evolution','http://localhost').id;other=database.createProject('Other','http://localhost').id;
 runId=service.runLedger().register({projectId:project,externalId:'fixture',idempotencyKey:'fixture',binding:{schemaVersion:1,models:captureWebModels().binding,skillVersion:'test',loadedDigest:'a'.repeat(64),materialsHash:null,inputHash:null,environmentHash:null,materialRevisions:[]} },system).runId;
 assets=new (await import('../src/projectAssets.js')).ProjectAssets(service.runLedger());tasks=new (await import('../src/projectTasks.js')).ProjectTasks(service.runLedger());discoveries=new (await import('../src/projectDiscoveries.js')).ProjectDiscoveries(service.runLedger());incremental=await import('../src/projectIncremental.js');
 const source=service.runLedger().putRevision({projectId:project,runId,name:'rules',kind:'material',content:{mode:'candidate'}},system);const v=assets.propose(project,{assetKey:'rules',sourceRevision:source.id,baseVersion:null},human);assets.decide(project,v.id,{action:'adopt',expectedHead:null,reason:'fixture'},human);snapshot=assets.snapshot(project,'Initial',human).id;
 ref=service.runLedger().putRevision({projectId:project,runId,name:'exploration/report',kind:'report',content:{observations:[{status:'attempted',featureId:'resource.close',stateAfter:'active',effect:{controlsAdded:['Partial close']}}]}},system).id;discovery=discoveries.list(project)[0]!.id;
});
afterAll(()=>{service.runLedger().close();database.db.close();vi.unstubAllEnvs();rmSync(dir,{recursive:true,force:true});});
const task=(goal:string,dependsOn:string[]=[])=>tasks.create(project,{snapshotId:snapshot,discoveryIds:[discovery],target:'stories',goal,dependsOn});
it('collects real receipts without promoting hypotheses; deduplicates receipts and rejects forgery',()=>{
 expect(discoveries.list(project)).toHaveLength(1);discoveries.capture(service.runLedger().readRevision(ref,project).revision,service.runLedger().readRevision(ref,project).content);expect(discoveries.read(project,discovery).refs).toEqual([ref]);expect(discoveries.read(project,discovery).trust).toBe('candidate');
 expect(()=>discoveries.record(other,{runId,evidenceRef:ref,category:'capability',featureId:'x',observation:'x'},human)).toThrow();
 const forged=service.runLedger().putRevision({projectId:project,runId,name:'forged',kind:'report',content:{}},{kind:'agent',id:'planner'});expect(()=>discoveries.record(project,{runId,evidenceRef:forged.id,category:'capability',featureId:'x',observation:'x'},human)).toThrow('discovery_requires_system_receipt');
});
it('leases prevent duplicate workers and late completion, dependencies block and budget terminates',()=>{
 const a=task('Lease fixture'),b=task('Dependency fixture',[a.id]);expect(()=>tasks.claim(project,b.id,'worker')).toThrow('task_dependencies_pending');const first=tasks.claim(project,a.id,'one',100);expect(()=>tasks.claim(project,a.id,'two',101)).toThrow('task_already_claimed');const second=tasks.claim(project,a.id,'two',400000);expect(()=>tasks.complete(project,a.id,first.lease!.token,{},400001)).toThrow('task_lease_invalid');tasks.complete(project,a.id,second.lease!.token,{},400001);tasks.decide(project,a.id,true,'reviewed',human);expect(tasks.claim(project,b.id,'worker',400002).status).toBe('claimed');
 const budget=task('Budget fixture');tasks.claim(project,budget.id,'x',1);tasks.claim(project,budget.id,'x',400000);expect(tasks.claim(project,budget.id,'x',800000).status).toBe('blocked');expect(()=>task('Bad dependency',['missing'])).toThrow('project_task_missing');
});
it('global planner creates candidate assets, bounded follow-ups and preserves original evidence',async()=>{
 const work=task('Add partial close goal');chat.mockResolvedValueOnce({text:JSON.stringify({summary:'Propose partial close',changes:[{assetKey:'story/partial-close',baseVersion:null,kind:'stories',content:{stories:[{id:'S-PARTIAL',title:'Partial close',requirementDraft:{reason:'Hypothesis',questions:['Confirm limits']},acceptance:['Remaining resource stays active','Reject excessive quantity']}]},dependencies:[],evidenceRefs:[ref],reason:'New control observed'}],followUps:[{target:'source',goal:'Observe partial close prerequisites',assetKeys:[]}]}),tokens:1,ms:1});
 const output=await incremental.runProjectTask(project,work.id);expect(output.status).toBe('review');const result=output.result as {candidateVersions:string[];runId:string};expect(service.runLedger().requireRun(result.runId,project).binding.inputHash).not.toBe(assets.readSnapshot(project,snapshot).digest);expect(assets.read(project,result.candidateVersions[0]).content).toHaveProperty('stories');expect(assets.heads(project)['story/partial-close']).toBeUndefined();expect(()=>tasks.decide(project,work.id,true,'x',{kind:'agent',id:'model'})).toThrow('operator_action_required');
 tasks.decide(project,work.id,true,'Reviewed proposal',human);const follow=incremental.materializeFollowUps(project,work.id);expect(follow).toHaveLength(1);expect(incremental.materializeFollowUps(project,work.id)[0].id).toBe(follow[0].id);expect(follow[0].dependsOn).toContain(work.id);expect(service.runLedger().readRevision(ref,project).revision.runId).toBe(runId);
});
it('rejects invented evidence and wrong base versions; clean plans cannot inherit snapshot or experience',async()=>{
 const work=task('Validate response'),context=incremental.incrementalContext(project,work.id);expect(()=>incremental.validateIncrementalProposal(context,{summary:'x',changes:[{assetKey:'rules',baseVersion:null,kind:'material',content:{},dependencies:[],evidenceRefs:[ref],reason:'x'}],followUps:[]})).toThrow('proposal_base_mismatch');
 const plans=await import('../src/projectRunPlans.js');const plan=plans.createProjectRunPlan(project,{mode:'clean',label:'Clean',configuration:{knowledgeSelection:null,rulePackSelection:null}});expect(plans.projectPlanInputs(project,plan.id).reuseExperience).toBe(false);expect(plan.configuration.knowledge).toEqual([]);expect(()=>plans.createProjectRunPlan(project,{mode:'clean',label:'Bad',configuration:{},snapshotId:snapshot})).toThrow('clean_plan_cannot_inherit_snapshot');
});
it('completes a second incremental cycle, preserves old snapshots and records a human comparison',async()=>{
 const first=assets.list(project).versions.find(v=>v.assetKey==='story/partial-close')!;assets.decide(project,first.id,{action:'adopt',expectedHead:null,reason:'Fixture human review'},human);
 const secondSnapshot=assets.snapshot(project,'Second cycle',human);
 const work=tasks.create(project,{snapshotId:secondSnapshot.id,discoveryIds:[discovery],target:'stories',goal:'Add rejection recovery',assetKeys:['story/partial-close']});
 chat.mockResolvedValueOnce({text:JSON.stringify({summary:'Add recovery',changes:[{assetKey:'story/partial-close',baseVersion:first.id,kind:'stories',content:{stories:[{id:'S-PARTIAL',title:'Partial close',acceptance:['Remaining active','Reject excess','Retry after correction']}]},dependencies:[],evidenceRefs:[ref],reason:'Recovery missing'}],followUps:[]}),tokens:1,ms:1});
 const done=await incremental.runProjectTask(project,work.id),second=(done.result as {candidateVersions:string[]}).candidateVersions[0];expect(assets.readSnapshot(project,snapshot).heads['story/partial-close']).toBeUndefined();expect(assets.heads(project)['story/partial-close']).toBe(first.id);
 const comparison=await import('../src/projectComparisons.js');const report=comparison.compareProjectAssets(project,first.id,second);expect(report.delta.acceptanceCriteria).toBe(1);expect(report.inputComparison.causalAttributionSupported).toBe(false);const reviewed=comparison.reviewProjectComparison(project,{before:first.id,after:second,verdict:'better',reason:'Fixture reviewer confirms recovery coverage'},human);expect(comparison.projectComparisons(project).map(r=>r.id)).toContain(reviewed.id);
 const plans=await import('../src/projectRunPlans.js');const clean=plans.createProjectRunPlan(project,{mode:'clean',label:'Clean after two cycles',configuration:{}});expect(JSON.stringify(clean.configuration)).not.toContain('S-PARTIAL');const reused=plans.createProjectRunPlan(project,{mode:'incremental',label:'Reuse',snapshotId:secondSnapshot.id,configuration:{}});expect(JSON.stringify(reused.configuration)).toContain('S-PARTIAL');
});
it('held-out results cannot enter project discoveries or reusable assets',()=>{
 const held=service.runLedger().register({projectId:project,externalId:'held-out',idempotencyKey:'held-out',binding:{schemaVersion:1,models:captureWebModels().binding,skillVersion:'fixture',loadedDigest:'a'.repeat(64),materialsHash:null,inputHash:null,environmentHash:null,materialRevisions:[]},parameters:{evaluationSplit:'held-out'}},system).runId;
 const before=discoveries.list(project).length;const observation=service.runLedger().putRevision({projectId:project,runId:held,name:'exploration/report',kind:'report',content:{observations:[{status:'blocked',featureId:'secret-eval',reason:'Missing fixture'}]}},system);expect(discoveries.list(project)).toHaveLength(before);
 expect(()=>discoveries.record(project,{runId:held,evidenceRef:observation.id,category:'missing_state',featureId:'secret-eval',observation:'secret'},human)).toThrow('held_out_discovery_not_reusable');
 const source=service.runLedger().putRevision({projectId:project,runId:held,name:'answers',kind:'material',content:{answer:42}},system);expect(()=>assets.propose(project,{assetKey:'answers',sourceRevision:source.id,baseVersion:null},human)).toThrow('held_out_asset_not_reusable');
});
it('rebuild namespaces cannot overwrite main assets, and snapshots isolate lineages',()=>{
 const line='line-fixture';const fresh=service.runLedger().register({projectId:project,externalId:'rebuild',idempotencyKey:'rebuild',binding:{schemaVersion:1,models:captureWebModels().binding,skillVersion:'fixture',loadedDigest:'a'.repeat(64),materialsHash:null,inputHash:null,environmentHash:null,materialRevisions:[]},parameters:{projectLineageId:line,projectRunMode:'rebuild',reuseExperience:false}},system).runId;
 const source=service.runLedger().putRevision({projectId:project,runId:fresh,name:'rules',kind:'material',content:{newLineage:true}},system);
 expect(()=>assets.propose(project,{assetKey:'rules',sourceRevision:source.id,baseVersion:null},human)).toThrow('asset_lineage_required');const v=assets.propose(project,{assetKey:line+'/rules',sourceRevision:source.id,baseVersion:null},human);assets.decide(project,v.id,{action:'adopt',expectedHead:null,reason:'Fixture review'},human);
 expect(assets.snapshot(project,'Main',human).heads[line+'/rules']).toBeUndefined();expect(Object.keys(assets.snapshot(project,'Rebuild',human,line).heads)).toEqual([line+'/rules']);
});

it('rejects a plan if project configuration changed after preview',async()=>{
 const plans=await import('../src/projectRunPlans.js');const plan=plans.createProjectRunPlan(project,{mode:'clean',label:'Before edit',configuration:{}});
 database.updateProject(project,{name:'Changed after plan'});expect(()=>plans.projectPlanInputs(project,plan.id)).toThrow('project_configuration_changed_replan');
});
it('malformed auxiliary report collections do not prevent artifact persistence',()=>{
 const revision=service.runLedger().putRevision({projectId:project,runId,name:'execution/malformed',kind:'execution',content:{results:{notAnArray:true},prerequisiteChecks:'invalid',status:'failed',failureReason:{message:'failure'}}},system);
 expect(service.runLedger().readRevision(revision.id,project).revision.id).toBe(revision.id);
});
