import {readProjectContext,navigateProject} from '@/lib/projectContext';
import { useEffect, useMemo, useState } from 'react';
import { useT } from '@/lib/prefs';
type Item=Record<string,unknown>;
export function ProductStructure({data,hideStories=false,onScope}:{data:Item;hideStories?:boolean;onScope?:(scope:Set<string>|null)=>void}) {
  const t=useT(),[selected,setSelected]=useState(()=>readProjectContext().scope),[query,setQuery]=useState('');
  useEffect(()=>{const h=()=>setSelected(readProjectContext().scope);window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);
  const selectModule=(id:string)=>{setSelected(id);navigateProject(new URLSearchParams(location.hash.split('?')[1]).get('open')??'canvas',{scope:id});};
  const modules=useMemo(()=>(Array.isArray(data.modules)?data.modules:[]) as Item[],[data]);
  const stories=(Array.isArray(data.stories)?data.stories:[]) as Item[];
  const selectedIds=useMemo(()=>{const ids=new Set([selected]);for(let i=0;i<modules.length;i++)for(const m of modules)if(ids.has(String(m.parentId??'')))ids.add(String(m.id));return ids;},[modules,selected]);
  useEffect(()=>onScope?.(selected?selectedIds:null),[onScope,selected,selectedIds]);
  const storyModules=(s:Item):string[]=>Array.isArray(s.moduleIds)?s.moduleIds.map(String):modules.filter(m=>String(m.name)===s.activity||(Array.isArray(m.flowIds)&&m.flowIds.includes(s.flowId))).map(m=>String(m.id));
  const filtered=stories.filter(s=>(!selected||storyModules(s).some(id=>selectedIds.has(id)))&&JSON.stringify(s).toLowerCase().includes(query.toLowerCase()));
  function tree(parent:string,depth=0):React.ReactNode{return depth>12?null:modules.filter(m=>String(m.parentId??'')===parent).map(m=><div key={String(m.id)} className="flex items-center gap-5"><button aria-pressed={selected===m.id} onClick={()=>selectModule(selected===m.id?'':String(m.id))} className={`w-44 shrink-0 rounded-lg border px-4 py-3 text-left text-sm ${selected===m.id?'border-primary bg-primary/10 text-primary':'border-border bg-card hover:border-primary'}`}><span className="font-medium">{String(m.name??m.id)}</span>{/* 还没有故事的时候不要在每个模块下面写「0 用户故事」：那是 modules 节点的正常状态，
        写出来像是每个模块都漏了故事。扇出要到 stories 合并之后才算得了（docs/v3/24 §8.5）。 */}
      {!hideStories&&<span className="mt-1 block text-xs text-muted-foreground">{stories.filter(s=>storyModules(s).includes(String(m.id))).length} {t('workflow.stage.stories')}</span>}</button>{modules.some(n=>n.parentId===m.id)&&<div className="space-y-3 border-l border-border pl-5">{tree(String(m.id),depth+1)}</div>}</div>);}
  return <div className="space-y-5">{modules.length>0&&<section aria-label={t('bench.productStructure')} className="overflow-auto rounded-lg border border-border bg-muted/20 p-5"><div className="mb-4 flex items-center gap-3"><h3 className="font-medium">{t('bench.productStructure')}</h3><button className="text-xs text-primary underline" onClick={()=>selectModule('')}>{t('bench.allModules')}</button></div><div className="flex min-w-max items-center gap-5"><button className="w-36 shrink-0 rounded-lg border border-primary/30 bg-primary/5 p-4 text-left text-sm text-primary" onClick={()=>selectModule('')}>{t('bench.allModules')}<span className="mt-2 block text-xs">{modules.length}{hideStories?'':` · ${stories.length} ${t('workflow.stage.stories')}`}</span></button><div className="grid grid-cols-2 gap-x-8 gap-y-3 border-l border-primary/30 pl-5">{tree('')}</div></div></section>}
    {!hideStories&&<><div className="flex items-center justify-between gap-3"><h3 className="font-medium">{t('workflow.stage.stories')} · {filtered.length}</h3><input aria-label={t('bench.searchStories')} placeholder={t('bench.searchStories')} value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 rounded border border-border bg-background px-3 py-2 text-sm"/></div>
    <div className="space-y-3">{filtered.map(s=><details key={String(s.id)} className="rounded-lg border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-medium">{String(s.id)} · {String(s.title)}<span className="ml-2 text-xs font-normal text-muted-foreground">{storyModules(s).map(id=>String(modules.find(m=>m.id===id)?.name??id)).join(' / ')}</span></summary><p className="mt-3 text-sm text-muted-foreground">{String(s.role??'')} · {String(s.benefit??'')}</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{Array.isArray(s.acceptance)&&s.acceptance.map((a,i)=><li key={i}>{String(a)}</li>)}</ul>{(Array.isArray(s.featureRefs)&&s.featureRefs.length>0||Array.isArray(s.ruleRefs)&&s.ruleRefs.length>0)&&<p className="mt-3 flex flex-wrap gap-1.5">{[...(Array.isArray(s.featureRefs)?s.featureRefs:[]).map(x=>['featureRefs',String(x)] as const),...(Array.isArray(s.ruleRefs)?s.ruleRefs:[]).map(x=>['ruleRefs',String(x)] as const)].map(([k,v],i)=><span key={k+i} className="rounded bg-muted px-1.5 py-0.5 text-[0.6875rem] text-muted-foreground"><span className="opacity-70">{k}</span> {v}</span>)}</p>}{s.source!=null&&<p className="mt-3 break-words text-xs text-muted-foreground">{String(s.source)}</p>}</details>)}</div></>}
  </div>;
}
