import {useEffect,useState} from 'react';
import {workflowRequest} from '@/lib/workflowRuns';
import {useT} from '@/lib/prefs';
import {Button} from '@/components/ui';
import {DocumentFields} from './ArtifactDocument';
type Finding={id:string;category:string;featureId:string;observation:string;hypothesis:string;status:string;refs:string[]};
type Task={id:string;goal:string;target:string;status:string;dependsOn:string[];attempts:number;maxAttempts:number;lease?:{until:number};reason?:string;result?:unknown};
export function ProjectEvolution({projectId,runId}:{projectId:string;runId?:string}){
 const t=useT(),base=`projects/${projectId}/assets`,[findings,setFindings]=useState<Finding[]>([]),[tasks,setTasks]=useState<Task[]>([]),[snapshots,setSnapshots]=useState<Array<{id:string;label:string}>>([]),[selected,setSelected]=useState<string[]>([]),[depends,setDepends]=useState<string[]>([]),[snapshot,setSnapshot]=useState(''),[goal,setGoal]=useState(''),[target,setTarget]=useState('stories'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){const [d,q,a]=await Promise.all([workflowRequest<{discoveries:Finding[]}>(base+'/discoveries'),workflowRequest<{tasks:Task[]}>(base+'/tasks'),workflowRequest<{snapshots:Array<{id:string;label:string}>}>(base)]);setFindings(d.discoveries);setTasks(q.tasks);setSnapshots(a.snapshots);}
 useEffect(()=>{let live=true;const load=()=>{if(live)void refresh().catch(e=>{if(live)setError(String(e));});};load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[base]);
 async function act(path:string,body:unknown){setBusy(true);setError('');try{await workflowRequest(base+path,body);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section className="mb-6 space-y-3 rounded border border-border p-4"><h2 className="font-semibold">{t('evolution.title')}</h2><p className="text-sm text-muted-foreground">{t('evolution.hint')}</p>{error&&<p role="alert" className="text-bad text-sm">{error}</p>}
 <Button disabled={busy} onClick={()=>void act('/discoveries/collect',runId?{runId}:{})}>{t('evolution.collect')}</Button>
 {findings.map(d=><details key={d.id} className="rounded border border-border p-3 text-sm"><summary><input aria-label={d.featureId} type="checkbox" disabled={d.status==='dismissed'} checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(id=>id!==d.id))}/> {d.featureId} · {d.category} · {d.status}</summary><p className="mt-2">{d.observation}</p><p>{d.hypothesis}</p><p className="break-all text-xs text-muted-foreground">{d.refs.join(', ')}</p><div className="mt-2 flex gap-2"><Button disabled={busy||!reason.trim()} onClick={()=>void act('/discoveries/'+d.id+'/decision',{status:'triaged',reason})}>{t('evolution.triage')}</Button><Button disabled={busy||!reason.trim()} onClick={()=>void act('/discoveries/'+d.id+'/decision',{status:'dismissed',reason})}>{t('evolution.dismiss')}</Button></div></details>)}
 <input className="w-full rounded border border-border bg-card p-2 text-sm" aria-label={t('assets.reason')} placeholder={t('assets.reason')} value={reason} onChange={e=>setReason(e.target.value)}/>
 <div className="space-y-2 rounded bg-muted p-3"><h3 className="text-sm font-medium">{t('evolution.newTask')}</h3><select className="max-w-full rounded border border-border bg-card p-2 text-sm" aria-label={t('plans.snapshot')} value={snapshot} onChange={e=>setSnapshot(e.target.value)}><option value="">{t('plans.snapshot')}</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select className="rounded border border-border bg-card p-2 text-sm" aria-label={t('evolution.target')} value={target} onChange={e=>setTarget(e.target.value)}>{['source','modules','stories','cases','rules'].map(n=><option key={n} value={n}>{n}</option>)}</select><textarea className="w-full rounded border border-border bg-card p-2 text-sm" aria-label={t('evolution.goal')} placeholder={t('evolution.goal')} value={goal} onChange={e=>setGoal(e.target.value)}/>
 <fieldset><legend className="text-sm">{t('evolution.dependencies')}</legend>{tasks.map(q=><label key={q.id} className="block text-xs"><input type="checkbox" checked={depends.includes(q.id)} onChange={e=>setDepends(e.target.checked?[...depends,q.id]:depends.filter(id=>id!==q.id))}/> {q.goal}</label>)}</fieldset><Button disabled={busy||!snapshot||!selected.length||!goal.trim()} onClick={()=>void act('/tasks',{snapshotId:snapshot,discoveryIds:selected,dependsOn:depends,goal,target})}>{t('evolution.newTask')}</Button></div>
 {tasks.map(q=><details key={q.id} className="rounded border border-border p-3 text-sm"><summary>{q.goal} · {q.status} · {q.attempts}/{q.maxAttempts}</summary><p className="break-all text-xs">{q.id} ← {q.dependsOn.join(', ')||'—'}</p>{q.reason&&<p>{q.reason}</p>}{q.result!=null&&<DocumentFields data={q.result}/>}
 <div className="mt-2 flex flex-wrap gap-2"><Button disabled={busy||!(q.status==='pending'||q.status==='claimed'&&(q.lease?.until??0)<Date.now())} onClick={()=>void act('/tasks/'+q.id+'/run',{})}>{t(q.target==='source'?'evolution.explore':'evolution.plan')}</Button>{q.status==='review'&&<><Button disabled={busy||!reason.trim()} onClick={()=>void act('/tasks/'+q.id+'/decision',{approve:true,reason})}>{t('evolution.accept')}</Button><Button disabled={busy||!reason.trim()} onClick={()=>void act('/tasks/'+q.id+'/decision',{approve:false,reason})}>{t('evolution.dismiss')}</Button></>}{q.status==='done'&&<Button disabled={busy} onClick={()=>void act('/tasks/'+q.id+'/follow-ups',{})}>{t('evolution.followups')}</Button>}</div></details>)}
 </section>;
}
