import { useEffect, useState } from 'react';
import { useT } from '@/lib/prefs';
import { workflowBase, workflowRequest } from '@/lib/workflowRuns';
interface RoleSpend {role:string;coverage:string;calls:number|null;inputTokens:number|null;outputTokens:number|null;cachedInputTokens:number|null;cacheWriteTokens:number|null;callMs:number|null;reportedUsd:number|null;estimatedUsd:number|null}
interface Spend {roles:RoleSpend[];wallMs:number|null;executionWallMs:number;records:Array<{role:string;source:string;priceVersion:string|null;caseRevision:string|null}>}
export function RunSpendPanel({projectId,runId,status}:{projectId:string;runId:string;status:string}){
 const t=useT(),[spend,setSpend]=useState<Spend|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const read=async()=>{try{const data=await workflowRequest<Spend>(`${workflowBase(projectId)}/${encodeURIComponent(runId)}/spend`,undefined,'GET',controller.signal);if(!controller.signal.aborted){setSpend(Array.isArray(data.roles)?data:null);setFailed(false);}}catch{if(!controller.signal.aborted)setFailed(true);}if(!controller.signal.aborted)timer=setTimeout(()=>void read(),5000);};void read();return()=>{controller.abort();clearTimeout(timer);};},[projectId,runId,status]);
 const number=(n:number|null|undefined)=>n==null?t('workflow.unknown'):n.toLocaleString(),usd=(n:number|null)=>n===null?t('workflow.unknown'):`$${n.toFixed(5)}`;
 return <section className="space-y-3 rounded-lg border border-border p-4" aria-label={t('spend.roles')}><h3 className="font-semibold">{t('spend.roles')}</h3><p className="text-xs text-muted-foreground">{t('spend.unknownNote')}</p>{failed?<p role="status" className="text-sm text-bad">{t('workflow.connectionError')}</p>:spend&&<><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border text-muted-foreground">{['role','calls','input','output','cached','writeCache','reported','estimated'].map(k=><th key={k} className="whitespace-nowrap py-2 pr-4 font-normal">{t(`spend.${k}`)}</th>)}</tr></thead><tbody>{spend.roles.map(row=><tr key={row.role} className="border-b border-border"><th className="py-3 pr-4 font-medium">{t(`modelRoles.${row.role}`)}<span className="mt-1 block font-normal text-muted-foreground">{t(`spend.${row.coverage}`)}</span></th>{[row.calls,row.inputTokens,row.outputTokens,row.cachedInputTokens,row.cacheWriteTokens].map((n,i)=><td key={i} className="py-3 pr-4 font-mono">{number(n)}</td>)}<td className="pr-4 font-mono">{usd(row.reportedUsd)}</td><td className="pr-4 font-mono">{usd(row.estimatedUsd)}</td></tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">{t('spend.executionWall')}: {number(Math.round(spend.executionWallMs/1000))}s · {t('spend.callTime')}: {spend.roles.map(r=>`${t(`modelRoles.${r.role}`)} ${r.callMs===null?t('workflow.unknown'):`${Math.round(r.callMs/1000)}s`}`).join(' / ')}</p><details className="text-xs"><summary className="cursor-pointer">{t('spend.priceEvidence')}</summary><pre className="mt-2 max-h-44 overflow-auto whitespace-pre-wrap break-all rounded bg-muted p-3">{JSON.stringify(spend.records.map(r=>({role:r.role,source:r.source,priceVersion:r.priceVersion,caseRevision:r.caseRevision})),null,2)}</pre></details></>}</section>;
}
