import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { dataPath } from "../datadir.js";

/**
 * 给服务端起的规划宿主（Claude Code / Codex / Penguin）打上「我是宿主」的标记。
 *
 * 本地复核不做身份验证（2026-09-10 用户决定），人和模型靠「请求带不带 Authorization / x-testpilot-actor」区分
 * （`reviewPrincipal.ts`）。2026-09-24 审查发现：规划器能跑 `node` / `curl`，裸 HTTP 不带头就被当成人——
 * 它可以自己批准故事、冻结模块树。这里不引入登录，只让宿主进程树里**默认的**发请求方式都自动带上
 * `x-testpilot-actor`：node（`NODE_OPTIONS --import` 预加载，包 fetch 与 http.request）、curl（`CURL_HOME/.curlrc`）、
 * wget（`WGETRC`）。只对发往 TestPilot 服务的请求加，别的请求（包括宿主自己的模型 API）不碰。
 * 这挡的是「顺手」，不是「蓄意」：刻意去掉头仍然能冒充，那需要身份验证，不在初步交付范围内。
 */
export const HOST_ACTOR = "planner-host";

const preload = (target: string) => `// generated by hostActorTag.ts — do not edit
const TARGET = ${JSON.stringify(target)};
const TAG = ${JSON.stringify(HOST_ACTOR)};
const hit = (u) => { try { const x = new URL(String(u)); return x.origin === TARGET || (x.port === new URL(TARGET).port && ['127.0.0.1','localhost','[::1]','0.0.0.0'].includes(x.hostname)); } catch { return false; } };
const nativeFetch = globalThis.fetch;
if (nativeFetch) globalThis.fetch = function (input, init) {
  const url = typeof input === 'string' || input instanceof URL ? input : input?.url;
  if (!hit(url)) return nativeFetch.call(this, input, init);
  const headers = new Headers(init?.headers ?? (input instanceof Request ? input.headers : undefined));
  if (!headers.has('x-testpilot-actor')) headers.set('x-testpilot-actor', TAG);
  return nativeFetch.call(this, input, { ...(init ?? {}), headers });
};
const withTag = (h) => Object.keys(h ?? {}).some(k => k.toLowerCase() === 'x-testpilot-actor') ? h : { ...(h ?? {}), 'x-testpilot-actor': TAG };
const tagHttp = async (name) => {
  const mod = (await import(name)).default;
  for (const fn of ['request', 'get']) {
    const orig = mod[fn];
    mod[fn] = function (a, b, c) {
      const url = typeof a === 'string' || a instanceof URL ? String(a) : \`\${name === 'node:https' ? 'https' : 'http'}://\${a?.hostname ?? a?.host ?? 'localhost'}:\${a?.port ?? ''}\`;
      if (hit(url)) {
        if (typeof a === 'string' || a instanceof URL) { if (b && typeof b === 'object') b = { ...b, headers: withTag(b.headers) }; else { c = b; b = { headers: withTag() }; } }
        else a = { ...a, headers: withTag(a.headers) };
      }
      return orig.call(this, a, b, c);
    };
  }
};
await tagHttp('node:http'); await tagHttp('node:https');
`;

/** 宿主进程的环境补丁：保留已有的 NODE_OPTIONS，追加预加载。 */
export function hostActorEnv(serverUrl: string, base: NodeJS.ProcessEnv = process.env): Record<string, string> {
  const dir = dataPath("host-actor");
  mkdirSync(dir, { recursive: true });
  const origin = new URL(serverUrl).origin;
  const file = join(dir, "tag.mjs");
  writeFileSync(file, preload(origin));
  writeFileSync(join(dir, ".curlrc"), `header = "x-testpilot-actor: ${HOST_ACTOR}"\n`);
  writeFileSync(join(dir, "wgetrc"), `header = x-testpilot-actor: ${HOST_ACTOR}\n`);
  const importFlag = `--import=${pathToFileURL(file).href}`;
  const existing = base.NODE_OPTIONS ?? "";
  return {
    NODE_OPTIONS: existing.includes(importFlag) ? existing : `${existing} ${importFlag}`.trim(),
    CURL_HOME: dir,
    WGETRC: join(dir, "wgetrc"),
    TP_HOST_ACTOR: HOST_ACTOR,
  };
}
