import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {canonicalJSON,type Principal} from '@testpilot/harness-core/run-contracts';
import {contentHash,LedgerError} from './runLedger.js';
import {runLedger} from './runService.js';
import {ProjectAssets} from './projectAssets.js';
export function assetMetrics(content:unknown){const c=content as any,stories=Array.isArray(c?.stories)?c.stories:[],cases=Array.isArray(c?.cases)?c.cases:[];return {stories:stories.length,cases:cases.length,acceptanceCriteria:stories.reduce((n:number,s:any)=>n+(Array.isArray(s.acceptance)?s.acceptance.length:0),0),candidateStories:stories.filter((s:any)=>s.requirementDraft).length,declaredTransitions:new Set(stories.flatMap((s:any)=>(s.businessTransitions??[]).map((b:any)=>b.transitionId))).size,duplicateStoryIds:stories.length-new Set(stories.map((s:any)=>s.id)).size,unobservedCriteria:stories.flatMap((s:any)=>s.observationLinks??[]).filter((l:any)=>l.status==='unobserved').length};}
export function compareProjectAssets(project:string,before:string,after:string){const ledger=runLedger(),assets=new ProjectAssets(ledger),a=assets.read(project,before),b=assets.read(project,after);if(a.version.assetKey!==b.version.assetKey||a.version.kind!==b.version.kind)throw new LedgerError(409,'comparison_requires_same_asset');const ar=ledger.requireRun(a.version.sourceRun,project),br=ledger.requireRun(b.version.sourceRun,project),x=assetMetrics(a.content),y=assetMetrics(b.content);const sameInputs=!!ar.binding.inputHash&&ar.binding.inputHash===br.binding.inputHash;const sameEnvironment=!!ar.binding.environmentHash&&ar.binding.environmentHash===br.binding.environmentHash;return {schemaVersion:'project-comparison.v1',before,after,assetKey:a.version.assetKey,inputComparison:{sameInputs,sameEnvironment,causalAttributionSupported:sameInputs&&sameEnvironment,beforeInput:ar.binding.inputHash,afterInput:br.binding.inputHash,beforeEnvironment:ar.binding.environmentHash,afterEnvironment:br.binding.environmentHash},beforeMetrics:x,afterMetrics:y,delta:Object.fromEntries(Object.keys(x).map(k=>[k,y[k as keyof typeof y]-x[k as keyof typeof x]])),notice:'Counts measure structure, not semantic quality or test passes. Different or unknown inputs/environment cannot establish a model improvement.',contentDigests:{before:a.version.contentHash,after:b.version.contentHash}};}
export function reviewProjectComparison(project:string,raw:unknown,actor:Principal){if(actor.kind!=='human')throw new LedgerError(403,'operator_action_required');const input=z.object({before:z.string(),after:z.string(),verdict:z.enum(['better','worse','tie','incomparable']),reason:z.string().trim().min(1).max(4000)}).strict().parse(raw),report=compareProjectAssets(project,input.before,input.after),row={id:'comparison-'+randomUUID(),projectId:project,...input,report,reportHash:contentHash(canonicalJSON(report)),actor,at:new Date().toISOString()};table();runLedger().db.prepare('INSERT INTO project_asset_comparisons VALUES(?,?,?)').run(row.id,project,canonicalJSON(row));return row;}
function table(){runLedger().db.exec('CREATE TABLE IF NOT EXISTS project_asset_comparisons(id TEXT PRIMARY KEY,projectId TEXT NOT NULL,json TEXT NOT NULL)');}
export function projectComparisons(project:string){table();return (runLedger().db.prepare('SELECT json FROM project_asset_comparisons WHERE projectId=? ORDER BY rowid DESC').all(project) as {json:string}[]).map(r=>JSON.parse(r.json));}
