import {compareProjectAssets,reviewProjectComparison,projectComparisons} from './projectComparisons.js';
import {startProjectTask,materializeFollowUps} from './projectIncremental.js';
import {ProjectTasks} from './projectTasks.js';
import {ProjectDiscoveries} from './projectDiscoveries.js';
import {createProjectRunPlan,readProjectRunPlan,projectPlanInputs} from './projectRunPlans.js';
import {createWebWorkflow} from './workflowOps.js';
import {Router} from 'express';
import {ProjectAssets} from './projectAssets.js';
import {assertProject,runLedger} from './runService.js';
import {LedgerError} from './runLedger.js';
import {reviewerPrincipal} from './reviewPrincipal.js';
export function projectAssetRouter(){
 const router=Router({mergeParams:true});
 router.use((req,res,next)=>{try{assertProject((req.params as {projectId:string}).projectId);next();}catch(e){res.status(e instanceof LedgerError?e.status:400).json({code:e instanceof LedgerError?e.code:'asset_request_invalid'});}});
 const wrap=(fn:(req:any)=>unknown)=>(req:any,res:any)=>{try{res.json(fn(req));}catch(e){res.status(e instanceof LedgerError?e.status:400).json({code:e instanceof LedgerError?e.code:'asset_request_invalid'});}};
 const store=()=>new ProjectAssets(runLedger());
 router.post('/plans',wrap(req=>{reviewerPrincipal(req);return createProjectRunPlan(req.params.projectId,req.body);}));
 router.get('/plans/:id',wrap(req=>readProjectRunPlan(req.params.projectId,req.params.id)));
 router.post('/plans/:id/start',async(req,res)=>{try{reviewerPrincipal(req);const project=(req.params as any).projectId;const plan=readProjectRunPlan(project,req.params.id);if(plan.runId){res.json({wfRunId:plan.runId,created:false});return;}const result=await createWebWorkflow(project,projectPlanInputs(project,req.params.id));runLedger().db.prepare('UPDATE project_run_plans SET runId=? WHERE id=?').run(result.wfRunId,plan.id);res.json(result);}catch(e){res.status(e instanceof LedgerError?e.status:400).json({code:e instanceof Error?e.message:'plan_start_failed'});}});
 router.get('/discoveries',wrap(req=>({discoveries:new ProjectDiscoveries(runLedger()).list(req.params.projectId)})));
 router.post('/discoveries/collect',wrap(req=>{reviewerPrincipal(req);const ledger=runLedger(),collector=new ProjectDiscoveries(ledger);for(const r of ledger.listRevisions(req.params.projectId,req.body.runId)){collector.capture(r,ledger.readRevision(r.id,req.params.projectId).content);}return {discoveries:collector.list(req.params.projectId)};}));
 router.post('/discoveries/:id/decision',wrap(req=>new ProjectDiscoveries(runLedger()).decide(req.params.projectId,req.params.id,req.body.status,req.body.reason,reviewerPrincipal(req))));
 router.post('/tasks/:id/run',(req,res)=>{try{reviewerPrincipal(req);const project=(req.params as any).projectId;new ProjectTasks(runLedger()).read(project,req.params.id);void startProjectTask(project,req.params.id);res.status(202).json({status:'queued'});}catch(e){res.status(e instanceof LedgerError?e.status:400).json({code:e instanceof Error?e.message:'task_start_failed'});}});
 router.post('/tasks/:id/rebaseline',wrap(req=>new ProjectTasks(runLedger()).rebaseline(req.params.projectId,req.params.id,req.body?.reason,reviewerPrincipal(req))));
 router.post('/tasks/:id/follow-ups',wrap(req=>{reviewerPrincipal(req);return {tasks:materializeFollowUps(req.params.projectId,req.params.id)};}));
 router.get('/tasks',wrap(req=>({tasks:new ProjectTasks(runLedger()).list(req.params.projectId)})));
 router.post('/tasks',wrap(req=>{reviewerPrincipal(req);return new ProjectTasks(runLedger()).create(req.params.projectId,req.body);}));
 router.post('/tasks/:id/decision',wrap(req=>new ProjectTasks(runLedger()).decide(req.params.projectId,req.params.id,req.body.approve===true,req.body.reason,reviewerPrincipal(req))));
 router.get('/impact/:id',wrap(req=>new ProjectTasks(runLedger()).impact(req.params.projectId,req.params.id)));
 router.get('/compare',wrap(req=>compareProjectAssets(req.params.projectId,String(req.query.before??''),String(req.query.after??''))));
 router.get('/comparisons',wrap(req=>({comparisons:projectComparisons(req.params.projectId)})));
 router.post('/comparisons',wrap(req=>reviewProjectComparison(req.params.projectId,req.body,reviewerPrincipal(req))));
 router.get('/',wrap(req=>store().list(req.params.projectId)));
 router.post('/candidates',wrap(req=>store().propose(req.params.projectId,req.body,reviewerPrincipal(req))));
 router.get('/versions/:id',wrap(req=>store().read(req.params.projectId,req.params.id)));
 router.post('/versions/:id/decision',wrap(req=>store().decide(req.params.projectId,req.params.id,req.body,reviewerPrincipal(req))));
 router.post('/snapshots',wrap(req=>store().snapshot(req.params.projectId,req.body.label,reviewerPrincipal(req),typeof req.body.lineageId==='string'?req.body.lineageId:'main')));
 router.get('/snapshots/:id',wrap(req=>store().readSnapshot(req.params.projectId,req.params.id)));
 return router;
}
