#!/usr/bin/env node
/** Local-only release audit. Never print secret values. */
import{execFileSync}from'node:child_process';import{readFileSync,existsSync,statSync,mkdirSync,writeFileSync}from'node:fs';import{resolve,join}from'node:path';import{createHash}from'node:crypto';
const root=resolve(import.meta.dirname,'..'),out=resolve(process.env.TP_EVIDENCE_DIR??join(root,'docs/v3/evidence/n-26'));mkdirSync(out,{recursive:true});
const hash=b=>createHash('sha256').update(b).digest('hex');
const files=[...new Set(execFileSync('git',['ls-files','-z','--cached','--others','--exclude-standard'],{cwd:root}).toString().split('\0').filter(Boolean))];
const secrets=[];const env=join(root,'server/.env');if(existsSync(env))for(const line of readFileSync(env,'utf8').split('\n')){const m=line.match(/^([A-Z0-9_]*(?:API_KEY|TOKEN|SECRET|PASSWORD))\s*=\s*["']?([^\r\n]+?)["']?\s*$/);if(m&&m[2].length>=12&&!m[2].includes('${'))secrets.push(m[2]);}
const findings=[],machineDefaults=[],inventory=[];for(const name of files){const path=join(root,name);if(!existsSync(path)||!statSync(path).isFile())continue;const size=statSync(path).size;if(!/\.(?:[cm]?[jt]sx?|jsonl?|md|ya?ml|html|toml|txt|log|css)$/.test(name))continue;const text=readFileSync(path,'utf8');for(const secret of secrets)if(text.includes(secret))findings.push({file:name,kind:'configured_secret_value'});
 if(/(?:api[_-]?key|authorization|writeToken|review[_-]?token)["']?\s*[:=]\s*["'](?:sk-[a-zA-Z0-9_-]{20,}|Bearer [a-zA-Z0-9_-]{40,})/i.test(text))findings.push({file:name,kind:'credential_shape_requires_review'});
 if(/^(server\/src|packages\/|apps\/|extensions\/|scripts\/testpilot-setup)/.test(name)&&/(?:["'`])\/(?:Users\/admin|opt\/homebrew|var\/folders)\//.test(text))machineDefaults.push({file:name,kind:'machine_path_in_implementation'});
 if(/^(server\/src|src\/|packages\/|apps\/|extensions\/|plugins\/|scripts\/)/.test(name))inventory.push({path:name,bytes:size,sha256:hash(text)});
}
const protectedFile=join(root,'docs/v3/evidence/n-14/protected-assets-sha256.json');let protectedCheck;
if(existsSync(protectedFile)){const baseline=JSON.parse(readFileSync(protectedFile,'utf8'));const entries=Array.isArray(baseline)?baseline:baseline.files??baseline;const rows=Array.isArray(entries)?entries:Object.entries(entries).map(([path,sha256])=>({path,sha256}));const differences=[];for(const r of rows){const p=r.path??r.file,expected=r.sha256??r.hash;if(typeof p!=='string'||typeof expected!=='string')continue;if(!existsSync(join(root,p))||hash(readFileSync(join(root,p)))!==expected)differences.push(p);}protectedCheck={checked:rows.length,differences};}
const report={at:new Date().toISOString(),branch:execFileSync('git',['branch','--show-current'],{cwd:root}).toString().trim(),head:execFileSync('git',['rev-parse','HEAD'],{cwd:root}).toString().trim(),configuredSecretValuesChecked:secrets.length,findings,machineDefaults,protectedCheck,implementationFiles:inventory.length,published:false};writeFileSync(join(out,'release-audit.json'),JSON.stringify(report,null,2));writeFileSync(join(out,'implementation-manifest.json'),JSON.stringify(inventory,null,2));console.log(JSON.stringify(report,null,2));if(findings.length||machineDefaults.length||protectedCheck?.differences.length)process.exitCode=1;
