/** Repeat the SAME immutable export on its original target; never regenerate it. */
import{config}from'dotenv';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{join,resolve,dirname}from'node:path';import{once}from'node:events';import{spawn}from'node:child_process';import{createRequire}from'node:module';import{executorConnectionFromEnv,openRoleProxy}from'@testpilot/harness-core';import{counterFixture}from'./lib/counter-fixture.js';
if(!process.argv.includes('--real'))throw new Error('--real required');const root=resolve(import.meta.dirname,'../..');config({path:join(root,'server/.env'),quiet:true}as any);const source=resolve(process.env.TP_PARITY_RESULT??join(root,'docs/v3/evidence/n-18/cold-warm-export-v3/result.json')),prior=JSON.parse(readFileSync(source,'utf8'));if(!prior.passed)throw new Error('successful_original_parity_required');const directory=join(prior.workspace,'exported');
const{verifyExport,assessP0,sha256}=await import('../../scripts/lib/p0-gate.mjs' as string);const frozen=readFileSync(join(dirname(source),'export-manifest.json')),expectedHash=sha256(frozen),manifest=JSON.parse(frozen.toString());if(manifest.cases.length!==1||manifest.cases[0].id!=='counter-1')throw new Error('counter_fixture_manifest_required');if(verifyExport(directory,expectedHash).status!=='verified')throw new Error('frozen_export_changed');
const url=new URL(manifest.cases[0].oracle.url);if(url.hostname!=='127.0.0.1'||url.protocol!=='http:'||url.pathname!=='/state')throw new Error('local_counter_target_required');
const model=executorConnectionFromEnv(),original=prior.exportRequests.find((r:any)=>r.forwarded);if(!original||original.model!==model.model||original.endpoint!==model.endpoint||original.thinking!==model.thinking)throw new Error('original_model_binding_required');
const out=resolve(process.env.TP_EVIDENCE_DIR??join(root,`docs/v3/evidence/n-18/repeat-${Date.now()}`));mkdirSync(out,{recursive:true});writeFileSync(join(out,'export-manifest.json'),frozen);const server=counterFixture();server.listen(Number(url.port),'127.0.0.1');await once(server,'listening');
const proxy=await openRoleProxy(model,undefined,{maxCalls:12,deadlineAt:Date.now()+300000});const chromium=createRequire(new URL('../../packages/harness-testing/package.json',import.meta.url))('puppeteer').executablePath();const env={...process.env,CI:'1',BASE_URL:url.origin,TP_APPROVED_EXPORT_SHA256:expectedHash,TP_CHROMIUM_EXECUTABLE_PATH:chromium,MIDSCENE_MODEL_BASE_URL:proxy.connection.endpoint,MIDSCENE_MODEL_API_KEY:proxy.connection.apiKey,MIDSCENE_MODEL_NAME:model.model};const trials:any[]=[];
try{for(let i=0;i<3;i++){const startedAt=new Date().toISOString(),chunks:Buffer[]=[];const child=spawn('npm',['test','--','--reporter=json'],{cwd:directory,env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>chunks.push(b));child.stderr.on('data',b=>chunks.push(b));const[code]=await once(child,'close');const finishedAt=new Date().toISOString();let text=Buffer.concat(chunks).toString();for(const key of[model.apiKey,proxy.connection.apiKey])text=text.split(key).join('[redacted]');writeFileSync(join(out,`trial-${i+1}.log`),text);let report;try{report=JSON.parse(text.slice(text.indexOf('{\n  "config":')))}catch{}const gate=assessP0({integrity:verifyExport(directory,expectedHash),executedManifestHash:expectedHash,startedAt,finishedAt,report});trials.push({index:i+1,startedAt,finishedAt,code,gate,report});console.log(JSON.stringify({trial:i+1,status:gate.status}));}}
finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await proxy.close();const passed=trials.length===3&&trials.every(t=>t.gate.status==='passed');writeFileSync(join(out,'result.json'),JSON.stringify({schemaVersion:1,type:'frozen-export-repeat-v1',passed,originalParity:source,workspace:prior.workspace,manifestHash:expectedHash,caseCount:1,trials,modelRequests:proxy.records},null,2));console.log(JSON.stringify({passed,evidence:out,manifestHash:expectedHash}));process.exitCode=passed?0:1;}
