/** Tool-scored exploratory action replay. All generated cases, unchanged oracles; no gold read. */
import {readFileSync,writeFileSync} from 'node:fs';import{resolve,join}from'node:path';import{once}from'node:events';import{createHash}from'node:crypto';
import{evaluateOracle}from'../../packages/harness-testing/src/exec/oracle.js';import{observeApi}from'../../packages/harness-testing/src/exec/apiOracle.js';
const out=resolve(process.argv[2]??'../docs/v3/evidence/n-16/repeated');const source=JSON.parse(readFileSync(join(out,'results.json'),'utf8'));
const {createPerpLab}=await import('../../fixtures/perp-lab/server.mjs' as string);const samples:any[]=[];
for(const run of source.results){for(const kase of run.bundle?.cases??[]){const sample:any={runId:run.runId,arm:run.arm,repetition:run.repetition,caseId:kase.id,caseHash:createHash('sha256').update(JSON.stringify(kase)).digest('hex'),oracle:kase.oracle,steps:kase.steps,observations:[]};
 let size:string|undefined,unsupported:string|undefined;
 for(const step of kase.steps){const match=step.match(/^Enter (\d+(?:\.\d+)?) in the Size field$/)??step.match(/^Set the Size field to (\d+(?:\.\d+)?)$/);if(match){if(size)unsupported='multiple_size_inputs';size=match[1];}
 else if(!['POST ${env.LAB_URL}/api/reset','GET ${env.LAB_URL}/api/clearinghouse','Select the Market tab','Click Place Order','Click “Place Order”'].includes(step))unsupported=step;}
 sample.input=size??null;
 for(const defect of [null,'round-size']){const server=createPerpLab({defect});server.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${server.address().port}`;
 try {if(unsupported||!size||kase.oracle?.kind!=='api'){sample.observations.push({defect,status:'unobservable',detail:unsupported??'unsupported_case'});continue;}
 await fetch(url+'/api/reset',{method:'POST'});const action=await fetch(url+'/api/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'market',size})});
 const api=await observeApi(kase.oracle,{env:{LAB_URL:url},secrets:{}});const verdict=evaluateOracle(kase.oracle,{text:'',url,api});sample.observations.push({defect,...verdict,httpStatus:action.status,api});
 }catch(e){sample.observations.push({defect,status:'infra',detail:(e as Error).message});}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}}
 const [healthy,bug]=sample.observations;sample.classification=healthy.status==='fail'?'FP':healthy.status!=='pass'||!['pass','fail'].includes(bug.status)?'unscored':bug.status==='fail'?'TP':'no_detection';samples.push(sample);}}
const arms=['off','on'].map(arm=>{const rows=samples.filter(r=>r.arm===arm);const runs=source.results.filter((r:any)=>r.arm===arm);const probe=rows.filter(r=>r.input==='0.0016');return{arm,runs:runs.length,validRuns:runs.filter((r:any)=>r.validBinding&&!r.error).length,cases:rows.length,healthyFalsePositives:rows.filter(r=>r.classification==='FP').length,killedCaseProbes:rows.filter(r=>r.classification==='TP').length,predeclaredFractionalProbe:{TP:probe.filter(r=>r.classification==='TP').length,FN:probe.filter(r=>r.classification==='no_detection').length,unscored:probe.filter(r=>r.classification==='unscored'||r.classification==='FP').length},unobservable:rows.flatMap(r=>r.observations).filter(r=>r.status==='unobservable').length,infra:rows.flatMap(r=>r.observations).filter(r=>r.status==='infra').length,distinctInputs:[...new Set(rows.map(r=>r.input))],wallMs:runs.map((r:any)=>r.wallMs)};});
const report={classification:'exploratory',formalEligible:false,reason:'Human gold freeze pending; one rule family and one controlled mutation, repeated generations are clustered.',adapter:'API action replay from allowlisted generated steps; every case reset independently; oracle bytes unchanged. This measures generated oracle discrimination, not UI grounding. Actual Midscene paired run is n-15/real-g1-oracle.',binding:{inputHash:source.spec.inputHash,datasetHash:source.spec.datasetHash,allCanariesValid:source.results.every((r:any)=>r.validBinding)},arms,samples,statistics:{significanceTest:null,reason:'Only one independent defect family; n=3 generations per arm does not create independent defect samples.'},conclusion:'No observed improvement in the predeclared fractional-size defect probe; both arms detect it in all three generations. Other probes and raw observations remain available.'};
writeFileSync(join(out,'scored.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({arms,binding:report.binding,conclusion:report.conclusion}));
