/** Synthetic gate fixtures exercise the real approval UI. Never human evidence. */
import{mkdtempSync,mkdirSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{once}from'node:events';import type{AddressInfo}from'node:net';import{randomBytes}from'node:crypto';import puppeteer from'puppeteer';
import{EvolutionStore,digest,type Score}from'../src/evolution/store.js';import{evaluationApp}from'../src/evolution/http.js';
const repo=resolve(import.meta.dirname,'../..'),workspace=mkdtempSync(join(tmpdir(),'tp-evolution-review-')),out=resolve(process.env.TP_EVIDENCE_DIR??join(repo,'docs/v3/evidence/n-24/synthetic-ui'));mkdirSync(out,{recursive:true});process.env.TP_EVOLUTION_DIR=workspace;process.env.TP_DATA_DIR=join(workspace,'testpilot');process.env.TP_EVOLUTION_ENVIRONMENT_LABEL='合成门禁验收 / SYNTHETIC GATE TEST — 不代表用户人工审核或真实质量提升';
const store=new EvolutionStore(workspace);const token=randomBytes(24).toString('hex');
const score=(value:number,memory:'off'|'scoped'):Score=>({policyHash:digest({memory}),score:value,p0Failures:0,unobservable:0,n:3,binding:{inputHash:'a'.repeat(64),datasetHash:'b'.repeat(64),rubricHash:'c'.repeat(64),runtime:'SYNTHETIC',model:'SYNTHETIC',replicates:3},source:'synthetic-gate-fixture'});
const c=store.create({synthetic:true});store.proposal(c.id,{memory:'off'});store.recordDevelopment(c.id,score(.5,'scoped'),score(1,'off'));
const app=evaluationApp(store,{start(){throw new Error('No model calls in synthetic fixture')}},token,repo,{heldout:async()=>({baseline:score(1,'scoped'),candidate:score(1,'off')}),hostRegression:async()=>({passed:true,policyHash:digest({memory:'off'}),source:'SYNTHETIC cross-host fixture; no real host regression'})});
const server=app.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
const {emptyRunBinding,runLedger}=await import('../src/runService.js');const {db}=await import('../src/db.js');const {captureWebModels}=await import('../test/helpers/model-snapshot.js');const models=captureWebModels().binding;const before=emptyRunBinding(models);
const browser=await puppeteer.launch({headless:true});let recording;
try{const page=await browser.newPage();await page.setViewport({width:1280,height:960});await page.goto(url);recording=await page.screencast({path:join(out,'review.webm'),ffmpegPath:process.env.FFMPEG_PATH??'ffmpeg'});
 const unauthorized=await fetch(`${url}/api/candidates/${c.id}/promote`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedGeneration:0,score:100,__actor:'human'})});if(unauthorized.status!==401)throw new Error('unauthenticated_promotion_allowed');
 await page.type('#token',token);await page.click('#auth button');await page.waitForFunction(()=>document.querySelector('#auth-status')!.textContent!.includes('已登录'));
 if(!(await page.$eval('[data-op=promote]',b=>(b as HTMLButtonElement).disabled)))throw new Error('premature_promote_enabled');
 await page.click('[data-op=heldout]');await page.waitForFunction(()=>document.querySelector('#candidates')!.textContent!.includes('host_regression_required'));
 await page.click('[data-op=host-regression]');await page.waitForFunction(()=>!(document.querySelector('[data-op=promote]') as HTMLButtonElement).disabled);await page.click('[data-op=promote]');await page.waitForFunction(()=>document.querySelector('#active-policy')!.textContent!.includes('off'));const promoted=emptyRunBinding(models);await page.screenshot({path:join(out,'promoted-synthetic.png'),fullPage:true});
 await page.type('#version',before.agentVersion!);await page.click('#rollback-button');await page.waitForFunction(()=>document.querySelector('#active-policy')!.textContent!.includes('scoped'));const restored=emptyRunBinding(models);await page.screenshot({path:join(out,'rollback-synthetic.png'),fullPage:true});
 if(before.contextPolicy?.memory!=='scoped'||promoted.contextPolicy?.memory!=='off'||restored.contextPolicy?.memory!=='scoped'||before.agentVersion!==restored.agentVersion)throw new Error('active_policy_snapshot_failure');
 writeFileSync(join(out,'result.json'),JSON.stringify({passed:true,synthetic:true,humanReviewEvidence:false,unauthorizedStatus:unauthorized.status,before:{version:before.agentVersion,policy:before.contextPolicy},promoted:{version:promoted.agentVersion,policy:promoted.contextPolicy},restored:{version:restored.agentVersion,policy:restored.contextPolicy},history:store.history()},null,2));console.log(JSON.stringify({passed:true,evidence:out,synthetic:true}));
}finally{await recording?.stop();await browser.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));store.close();db.close();}
