/** Controlled defect -> actual exported failure -> fixture fix -> actual exported pass; tamper and outage. */
import{config}from'dotenv';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{resolve,join}from'node:path';import{createServer}from'node:http';import{once}from'node:events';import{spawn}from'node:child_process';import{createRequire}from'node:module';
import{executorConnectionFromEnv,openRoleProxy}from'@testpilot/harness-core';
const root=resolve(import.meta.dirname,'../..');if(!process.argv.includes('--real'))throw new Error('--real required');config({path:join(root,'server/.env'),quiet:true}as any);
const input=resolve(process.env.TP_PARITY_RESULT??join(root,'docs/v3/evidence/n-18/cold-warm-export-v3/result.json')),previous=JSON.parse(readFileSync(input,'utf8'));if(!previous.passed)throw new Error('successful_export_parity_required');
const directory=join(previous.workspace,'exported'),manifest=JSON.parse(readFileSync(join(directory,'testpilot-manifest.json'),'utf8'));const oracle=manifest.cases[0].oracle,url=new URL(oracle.url).origin;
const {verifyExport,assessP0,sha256}=await import('../../scripts/lib/p0-gate.mjs' as string);const expectedHash=sha256(readFileSync(join(directory,'testpilot-manifest.json'))),out=join(root,'docs/v3/evidence/n-19/real-export');mkdirSync(out,{recursive:true});
let defect=true,count=0,closed=false;const server=createServer((req,res)=>{if(req.url==='/state'){res.setHeader('content-type','application/json');res.end(JSON.stringify({count}));}else if(req.url==='/increment'){count+=defect?2:1;res.end(String(count));}else if(req.url==='/'){count=0;res.setHeader('content-type','text/html');res.end('<!doctype html><html><title>Counter</title><body style="font:28px system-ui;padding:72px"><h1>Counter</h1><p>count: <span id="count">0</span></p><button style="font:24px system-ui;padding:20px" onclick="fetch(\'/increment\',{method:\'POST\'}).then(r=>r.text()).then(n=>document.getElementById(\'count\').textContent=n)">Increment</button></body></html>');}else{res.statusCode=404;res.end();}});server.listen(Number(new URL(url).port),'127.0.0.1');await once(server,'listening');
const model=executorConnectionFromEnv(),proxy=await openRoleProxy(model,undefined,{maxCalls:20,deadlineAt:Date.now()+300000});const binary=createRequire(new URL('../../packages/harness-testing/package.json',import.meta.url))('puppeteer').executablePath();
const env={...process.env,CI:'1',TP_APPROVED_EXPORT_SHA256:expectedHash,BASE_URL:url,TP_CHROMIUM_EXECUTABLE_PATH:binary,MIDSCENE_MODEL_BASE_URL:proxy.connection.endpoint,MIDSCENE_MODEL_API_KEY:proxy.connection.apiKey,MIDSCENE_MODEL_NAME:model.model};const scenarios:any[]=[];
async function execute(name:string){const startedAt=new Date().toISOString(),chunks:Buffer[]=[];const child=spawn('npm',['test','--','--reporter=json'],{cwd:directory,env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>chunks.push(b));child.stderr.on('data',b=>chunks.push(b));const [code]=await once(child,'close');let text=Buffer.concat(chunks).toString().split(model.apiKey).join('[redacted]').split(proxy.connection.apiKey).join('[redacted]');writeFileSync(join(out,name+'.log'),text);const start=text.indexOf('{\n  "config":');let report:any;try{report=JSON.parse(text.slice(start));}catch{}const finishedAt=new Date().toISOString(),integrity=verifyExport(directory,expectedHash);const gate=assessP0({integrity,report,executedManifestHash:expectedHash,startedAt,finishedAt});const result={scenario:name,code,startedAt,finishedAt,gate,report};scenarios.push(result);return result;}
try{await execute('known-defect');defect=false;await execute('fixture-repaired');
 const spec=Object.keys(manifest.files).find(p=>p.endsWith('.spec.ts'))!,path=join(directory,spec),original=readFileSync(path,'utf8');try{writeFileSync(path,original.replace('"value":1','"value":0'));scenarios.push({scenario:'weakened-oracle',gate:verifyExport(directory,expectedHash),executed:false});}finally{writeFileSync(path,original);}
 server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));closed=true;await execute('service-outage');
}finally{if(!closed){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await proxy.close();const passed=scenarios.map(r=>r.gate.status).join(',')==='failed,passed,blocked,blocked';writeFileSync(join(out,'result.json'),JSON.stringify({passed,expectedHash,sourceParity:input.slice(root.length+1),scenarios,modelRequests:proxy.records,remoteCI:false,repairActor:'controlled fixture switch, not autonomous agent repair',approvalActor:'synthetic integration approval, not human approval'},null,2));console.log(JSON.stringify({passed,scenarios:scenarios.map(r=>({scenario:r.scenario,gate:r.gate})),evidence:out}));process.exitCode=passed?0:1;}
