import{counterFixture}from'./lib/counter-fixture.js';
/** Actual Midscene cold/warm/action revision and independently installed exported Playwright suite. */
import{config}from'dotenv';import{readFileSync,writeFileSync,mkdirSync,mkdtempSync}from'node:fs';import{resolve,join,dirname}from'node:path';import{tmpdir}from'node:os';import{createServer}from'node:http';import{once}from'node:events';import{spawn}from'node:child_process';import{createRequire}from'node:module';
import{executorConnectionFromEnv,openRoleProxy}from'@testpilot/harness-core';import{executeRun}from'@testpilot/harness-testing/exec';
if(!process.argv.includes('--real'))throw new Error('--real required');const root=resolve(import.meta.dirname,'../..');config({path:join(root,'server/.env'),quiet:true}as any);
const out=resolve(process.env.TP_EVIDENCE_DIR??join(root,`docs/v3/evidence/n-18/real-${Date.now()}`));mkdirSync(out,{recursive:true});const workspace=mkdtempSync(join(tmpdir(),'tp-clean-export-'));process.env.TP_DATA_DIR=join(workspace,'data');process.env.MIDSCENE_CACHE='1';
const server=counterFixture();server.listen(Number(process.env.TP_PARITY_PORT??0),'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${(server.address()as any).port}`;
const oracle={kind:'api' as const,url:url+'/state',method:'GET' as const,path:'count',op:'eq' as const,value:1,settleMs:0};const executor=executorConnectionFromEnv();const runs:any[]=[];
function command(cmd:string,args:string[],cwd:string,env:NodeJS.ProcessEnv,log:string){return new Promise<number>((done,reject)=>{const child=spawn(cmd,args,{cwd,env,stdio:['ignore','pipe','pipe']});const lines:Buffer[]=[];child.stdout.on('data',b=>lines.push(b));child.stderr.on('data',b=>lines.push(b));child.on('error',reject);child.on('close',code=>{let text=Buffer.concat(lines).toString();for(const key of [executor.apiKey,env.MIDSCENE_OPENAI_API_KEY,env.OPENAI_API_KEY].filter(Boolean))text=text.split(key!).join('[redacted]');writeFileSync(join(out,log),text);done(code??1);});});}
let installed:number|null=null,exportCode:number|null=null,exportRequests:any[]=[];
try{
 for(const scenario of ['cold','warm','action-revision']){const steps=[scenario==='action-revision'?'Click the Increment button':'Click Increment'];const result=await executeRun(url,steps,'Count equals 1',{executorModel:executor,oracle,cacheId:'n18-shared-counter',modelBudget:{maxCalls:8,deadlineAt:Date.now()+120000}});const{pngBuffers,screenshots:_,...publicResult}=result;runs.push({scenario,steps,oracle,result:publicResult});for(let i=0;i<pngBuffers.length;i++)writeFileSync(join(out,`${scenario}-${i}.png`),pngBuffers[i]);console.log(JSON.stringify({scenario,status:result.status,calls:result.modelRequests?.length}));}
 const {buildExportFiles}=await import('../src/export.js');const files=buildExportFiles({id:'export-probe',name:'Counter parity',targetUrl:url}as any,[{id:'counter-1',projectId:'export-probe',title:'Counter reaches one',priority:'P0',type:'boundary',steps:[{order:1,text:'Click Increment'}],postSteps:[],expected:'Count equals 1',oracle}as any]);
 const exported=join(workspace,'exported');mkdirSync(exported,{recursive:true});for(const[p,s]of Object.entries(files)){mkdirSync(dirname(join(exported,p)),{recursive:true});writeFileSync(join(exported,p),s);}
 writeFileSync(join(out,'export-manifest.json'),files['testpilot-manifest.json']);
 const cleanEnv={...process.env,CI:'',MIDSCENE_CACHE:'0'};installed=await command('npm',['install','--no-audit','--no-fund'],exported,cleanEnv,'clean-install.log');if(installed!==0)throw new Error('clean_export_install_failed');
 const proxy=await openRoleProxy(executor,undefined,{maxCalls:8,deadlineAt:Date.now()+180000});try{const req=createRequire(new URL('../../packages/harness-testing/package.json',import.meta.url));const binary=req('puppeteer').executablePath();
 const env={...cleanEnv,BASE_URL:url,TP_CHROMIUM_EXECUTABLE_PATH:binary,OPENAI_BASE_URL:proxy.connection.endpoint,OPENAI_API_KEY:proxy.connection.apiKey,MIDSCENE_MODEL_NAME:executor.model,MIDSCENE_OPENAI_BASE_URL:proxy.connection.endpoint,MIDSCENE_OPENAI_API_KEY:proxy.connection.apiKey,MIDSCENE_MODEL_BASE_URL:proxy.connection.endpoint,MIDSCENE_MODEL_API_KEY:proxy.connection.apiKey,MIDSCENE_USE_QWEN3_VL:'0'};
 exportCode=await command('npm',['test','--','--reporter=json'],exported,env,'export-execution.log');exportRequests=proxy.records;
 }finally{await proxy.close();}
}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));const passed=runs.length===3&&runs.every(r=>r.result.status==='passed')&&exportCode===0;writeFileSync(join(out,'result.json'),JSON.stringify({passed,workspace,installed,exportCode,runs,exportRequests,notes:['Action-revision is a deliberate wording change, not a claim of autonomous repair.','Only executor cost is exercised here; planner is absent from this test.','Independent npm install in a fresh directory, using the already installed Chromium binary.','Single-session repetition is not five-night stability evidence.']},null,2));console.log(JSON.stringify({passed,evidence:out,installed,exportCode}));process.exitCode=passed?0:1;}
