/** Isolated real-browser integration; no SUT interaction or model invocation. */
import {chromium,expect} from '@playwright/test';
import {spawn} from 'node:child_process';import {mkdtempSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createServer} from 'node:net';
import {captureWebModels} from '../test/helpers/model-snapshot.js';
const dir=mkdtempSync(join(tmpdir(),'tp-evolution-ui-'));process.env.TP_DATA_DIR=join(dir,'data');process.env.TP_INSTANCE='test';
const db=await import('../src/db.js'),service=await import('../src/runService.js');const project=db.createProject('Evolution UI fixture','http://example.invalid');const actor={kind:'system' as const,id:'fixture'};
const run=service.runLedger().register({projectId:project.id,externalId:'fixture',idempotencyKey:'fixture',binding:{schemaVersion:1,models:captureWebModels().binding,skillVersion:'fixture',loadedDigest:'a'.repeat(64),materialsHash:null,inputHash:null,environmentHash:null,materialRevisions:[]}},actor).runId;
const material=service.runLedger().putRevision({projectId:project.id,runId:run,name:'fixture-rules',kind:'material',content:{rule:'Preserve remaining resource'}},actor);
service.runLedger().putRevision({projectId:project.id,runId:run,name:'exploration/report',kind:'report',content:{observations:[{status:'attempted',featureId:'resource.partial-close',stateAfter:'active',effect:{controlsAdded:['Partial close']}}]}},actor);
const secondMaterial=service.runLedger().putRevision({projectId:project.id,runId:run,name:'fixture-rules',kind:'material',parentRevision:material.id,content:{rule:'Preserve remaining resource; reject excessive quantity'}},actor);
service.runLedger().close();db.db.close();
const reservation=createServer();await new Promise<void>(r=>reservation.listen(0,'127.0.0.1',r));const port=(reservation.address() as {port:number}).port;await new Promise<void>(r=>reservation.close(()=>r()));
const backend=spawn('pnpm',['exec','tsx','src/index.ts'],{cwd:resolve(import.meta.dirname,'..'),env:{...process.env,PORT:String(port)},detached:true,stdio:['ignore','pipe','pipe']});let logs='';backend.stdout.on('data',c=>logs+=c);backend.stderr.on('data',c=>logs+=c);
const api=`http://127.0.0.1:${port}/api`,base=`${api}/projects/${project.id}/assets`;
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 let ready=false;for(let i=0;i<80;i++){try{if((await fetch(api+'/projects')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,250));}if(!ready)throw new Error('backend unavailable: '+logs.slice(-2000));
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://localhost:5300/?api=${encodeURIComponent('http://127.0.0.1:'+port)}#/?open=artifacts&project=${project.id}&run=${run}&artifact=${material.id}`);
 const library=page.getByRole('heading',{name:'项目资产版本',exact:true}).locator('..');await expect(library).toBeVisible();await library.getByRole('button',{name:'登记为候选版本',exact:true}).click();
 await expect.poll(async()=>((await (await fetch(base)).json()).versions as any[]).length).toBe(1);let state=await (await fetch(base)).json();const version=state.versions[0].id;
 await library.getByLabel('资产版本',{exact:true}).selectOption(version);await library.getByLabel('审核理由',{exact:true}).fill('Fixture reviewer confirms this candidate');await library.getByRole('button',{name:'采纳到项目资产',exact:true}).click();
 await expect.poll(async()=>(await (await fetch(base)).json()).heads['fixture-rules']).toBe(version);
 await library.getByLabel('快照名称',{exact:true}).fill('UI baseline');await library.getByRole('button',{name:'保存已采纳版本快照',exact:true}).click();await expect.poll(async()=>(await (await fetch(base)).json()).snapshots.length).toBe(1);state=await (await fetch(base)).json();
 const evolution=page.getByRole('heading',{name:'项目发现与增量任务',exact:true}).locator('..');await evolution.getByLabel('resource.partial-close',{exact:true}).check();await evolution.getByLabel('选择资产快照',{exact:true}).selectOption(state.snapshots[0].id,{timeout:12000});await evolution.getByLabel('任务目标与完成条件',{exact:true}).fill('Propose partial close and rejection stories');await evolution.getByRole('button',{name:'创建增量任务',exact:true}).click();await expect.poll(async()=>(await (await fetch(base+'/tasks')).json()).tasks.length).toBe(1);await evolution.locator('summary').filter({hasText:'Propose partial close and rejection stories'}).click();await expect(evolution.getByRole('button',{name:'分析并提出修订',exact:true})).toBeEnabled();
 const candidate=await (await fetch(base+'/candidates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetKey:'fixture-rules',sourceRevision:secondMaterial.id,baseVersion:version,dependencies:[]})})).json();
 await page.reload();const comparisons=page.getByRole('heading',{name:'项目资产版本',exact:true}).locator('..');await comparisons.getByLabel('资产版本',{exact:true}).selectOption(candidate.id);await comparisons.getByRole('combobox',{name:'选择比较基线版本',exact:true}).selectOption(version);await comparisons.getByRole('button',{name:'比较结构与输入',exact:true}).click();await comparisons.getByLabel('审核理由',{exact:true}).fill('Added excessive quantity condition; fixture review only');await comparisons.getByRole('button',{name:'保存人工评测及理由',exact:true}).click();await expect.poll(async()=>(await (await fetch(base+'/comparisons')).json()).comparisons.length).toBe(1);await expect(comparisons.locator('summary').filter({hasText:'人工评测记录 · 1'})).toBeVisible();
 await page.screenshot({path:join(dir,'project-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(dir,'project-mobile.png'),fullPage:true});
 await page.goto(`http://localhost:5300/?api=${encodeURIComponent('http://127.0.0.1:'+port)}#/?open=canvas&project=${project.id}&run=${run}`);await page.getByRole('button',{name:'新建测试运行',exact:true}).first().click();await expect(page.getByRole('combobox',{name:'运行方式',exact:true})).toHaveValue('clean');await page.getByRole('combobox',{name:'运行方式',exact:true}).selectOption('incremental');await expect(page.getByRole('combobox',{name:'选择资产快照',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'运行方式',exact:true}).selectOption('rebuild');await expect(page.getByRole('combobox',{name:'运行方式',exact:true})).toHaveValue('rebuild');
 if(errors.length)throw new Error(errors.join('\n'));writeFileSync(join(dir,'result.json'),JSON.stringify({passed:true,isolated:true,modelCalls:0,sutActions:0,projectId:project.id,run,version,errors},null,2));console.log(JSON.stringify({passed:true,evidence:dir}));
}finally{await browser.close();if(backend.pid)process.kill(-backend.pid,'SIGTERM');writeFileSync(join(dir,'backend.log'),logs);}
